package com.banry.pscm.service.util;

public class ContractAtt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_att.file_in_name
     *
     * @mbg.generated Wed Jun 13 14:02:24 CST 2018
     */
    private String fileInName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_att.type
     *
     * @mbg.generated Wed Jun 13 14:02:24 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_att.actual_file_name
     *
     * @mbg.generated Wed Jun 13 14:02:24 CST 2018
     */
    private String actualFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_att.location
     *
     * @mbg.generated Wed Jun 13 14:02:24 CST 2018
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_att.file_in_name
     *
     * @return the value of contract_att.file_in_name
     *
     * @mbg.generated Wed Jun 13 14:02:24 CST 2018
     */
    public String getFileInName() {
        return fileInName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_att.file_in_name
     *
     * @param fileInName the value for contract_att.file_in_name
     *
     * @mbg.generated Wed Jun 13 14:02:24 CST 2018
     */
    public void setFileInName(String fileInName) {
        this.fileInName = fileInName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_att.type
     *
     * @return the value of contract_att.type
     *
     * @mbg.generated Wed Jun 13 14:02:24 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_att.type
     *
     * @param type the value for contract_att.type
     *
     * @mbg.generated Wed Jun 13 14:02:24 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_att.actual_file_name
     *
     * @return the value of contract_att.actual_file_name
     *
     * @mbg.generated Wed Jun 13 14:02:24 CST 2018
     */
    public String getActualFileName() {
        return actualFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_att.actual_file_name
     *
     * @param actualFileName the value for contract_att.actual_file_name
     *
     * @mbg.generated Wed Jun 13 14:02:24 CST 2018
     */
    public void setActualFileName(String actualFileName) {
        this.actualFileName = actualFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_att.location
     *
     * @return the value of contract_att.location
     *
     * @mbg.generated Wed Jun 13 14:02:24 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_att.location
     *
     * @param location the value for contract_att.location
     *
     * @mbg.generated Wed Jun 13 14:02:24 CST 2018
     */
    public void setLocation(String location) {
        this.location = location;
    }
}