package com.banry.pscm.persist.dao;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import com.banry.pscm.persist.mapper.ConstantSqlProvider;
import com.banry.pscm.service.util.Constant;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface ConstantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constant
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @Delete({
        "delete from constant",
        "where constant_name = #{constantName,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String constantName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constant
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @Insert({
        "insert into constant (constant_name, constant_value, ",
        "remark)",
        "values (#{constantName,jdbcType=VARCHAR}, #{constantValue,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR})"
    })
    int insert(Constant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constant
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @InsertProvider(type=ConstantSqlProvider.class, method="insertSelective")
    int insertSelective(Constant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constant
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @Select({
        "select",
        "constant_name, constant_value, remark",
        "from constant",
        "where constant_name = #{constantName,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="constant_name", property="constantName", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="constant_value", property="constantValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    Constant selectByPrimaryKey(String constantName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constant
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @UpdateProvider(type=ConstantSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Constant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constant
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @Update({
        "update constant",
        "set constant_value = #{constantValue,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where constant_name = #{constantName,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Constant record);


    @SelectProvider(type = ConstantSqlProvider.class, method = "selectAll")
    List<Constant> selectAll();
}