package com.banry.pscm.persist.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.banry.pscm.persist.mapper.DivConsSchemeSqlProvider;
import com.banry.pscm.service.schedule.DivConsScheme;

public interface DivConsSchemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table div_cons_scheme
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @Delete({
        "delete from div_cons_scheme",
        "where scheme_code = #{schemeCode,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String schemeCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table div_cons_scheme
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @Insert({
        "insert into div_cons_scheme (scheme_code, division_sn_code, ",
        "div_level, name, scheme_type, ",
        "description, scheme_version, ",
        "submitter, version_date, ",
        "status, scheme_path, ",
        "scheme_attach)",
        "values (#{schemeCode,jdbcType=VARCHAR}, #{divisionSnCode,jdbcType=VARCHAR}, ",
        "#{divLevel,jdbcType=CHAR}, #{name,jdbcType=VARCHAR}, #{schemeType,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{schemeVersion,jdbcType=VARCHAR}, ",
        "#{submitter,jdbcType=VARCHAR}, #{versionDate,jdbcType=DATE}, ",
        "#{status,jdbcType=INTEGER}, #{schemePath,jdbcType=VARCHAR}, ",
        "#{schemeAttach,jdbcType=VARCHAR})"
    })
    int insert(DivConsScheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table div_cons_scheme
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @InsertProvider(type=DivConsSchemeSqlProvider.class, method="insertSelective")
    int insertSelective(DivConsScheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table div_cons_scheme
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @Select({
        "select",
        "scheme_code, division_sn_code, div_level, name, scheme_type, description, scheme_version, ",
        "submitter, version_date, status, scheme_path, scheme_attach",
        "from div_cons_scheme",
        "where scheme_code = #{schemeCode,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="scheme_code", property="schemeCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="division_sn_code", property="divisionSnCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="div_level", property="divLevel", jdbcType=JdbcType.CHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="scheme_type", property="schemeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="scheme_version", property="schemeVersion", jdbcType=JdbcType.VARCHAR),
        @Result(column="submitter", property="submitter", jdbcType=JdbcType.VARCHAR),
        @Result(column="version_date", property="versionDate", jdbcType=JdbcType.DATE),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="scheme_path", property="schemePath", jdbcType=JdbcType.VARCHAR),
        @Result(column="scheme_attach", property="schemeAttach", jdbcType=JdbcType.VARCHAR)
    })
    DivConsScheme selectByPrimaryKey(String schemeCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table div_cons_scheme
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @UpdateProvider(type=DivConsSchemeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(DivConsScheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table div_cons_scheme
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @Update({
        "update div_cons_scheme",
        "set division_sn_code = #{divisionSnCode,jdbcType=VARCHAR},",
          "div_level = #{divLevel,jdbcType=CHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "scheme_type = #{schemeType,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "scheme_version = #{schemeVersion,jdbcType=VARCHAR},",
          "submitter = #{submitter,jdbcType=VARCHAR},",
          "version_date = #{versionDate,jdbcType=DATE},",
          "status = #{status,jdbcType=INTEGER},",
          "scheme_path = #{schemePath,jdbcType=VARCHAR},",
          "scheme_attach = #{schemeAttach,jdbcType=VARCHAR}",
        "where scheme_code = #{schemeCode,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(DivConsScheme record);
    
    /**
	 * @param divisionSnCode
	 * @return
	 */
	@Select({"select ","scheme_code,division_sn_code,div_level,name,scheme_type,description,"
    		+ "scheme_version,submitter,version_date,status,scheme_path,scheme_attach ",
    	"from div_cons_scheme ","where division_sn_code = #{divisionSnCode,jdbcType=VARCHAR} "})
    @Results(id="BaseDivConsScheme",value={
    	@Result(column = "scheme_code", property = "schemeCode", jdbcType = JdbcType.VARCHAR, id = true),
		@Result(column = "division_sn_code", property = "divisionSnCode", jdbcType = JdbcType.VARCHAR),
		@Result(column = "div_level", property = "divLevel", jdbcType = JdbcType.CHAR),
		@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
		@Result(column = "scheme_type", property = "schemeType", jdbcType = JdbcType.VARCHAR),
		@Result(column = "description", property = "description", jdbcType = JdbcType.VARCHAR),
		@Result(column = "scheme_version", property = "schemeVersion", jdbcType = JdbcType.VARCHAR),
		@Result(column = "submitter", property = "submitter", jdbcType = JdbcType.VARCHAR),
		@Result(column = "version_date", property = "versionDate", jdbcType = JdbcType.DATE),
		@Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER),
		@Result(column = "scheme_path", property = "schemePath", jdbcType = JdbcType.VARCHAR),
		@Result(column = "scheme_attach", property = "schemeAttach", jdbcType = JdbcType.VARCHAR)
    })
	List<DivConsScheme> findDivConsSchemesByDivisionSnCode(@Param("divisionSnCode") String divisionSnCode);
	
	/**
	 * @param name
	 * @return
	 */
    @Select({"select ","scheme_code,division_sn_code,div_level,name,scheme_type,description,"
    		+ "scheme_version,submitter,version_date,status,scheme_path,scheme_attach ",
    	"from div_cons_scheme ","where name like concat('%',#{name,jdbcType=VARCHAR},'%') "})
    @ResultMap("BaseDivConsScheme")
	List<DivConsScheme> findDivConsSchemesByName(String name);
    
    /**
	 * @return
	 */
    @Select({"select ","scheme_code,division_sn_code,div_level,name,scheme_type,description,"
    		+ "scheme_version,submitter,version_date,status,scheme_path,scheme_attach ",
    	"from div_cons_scheme "})
    @ResultMap("BaseDivConsScheme")
	List<DivConsScheme> findAllDivConsScheme();
}