package com.banry.pscm.persist.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.banry.pscm.persist.mapper.EngDivisionPlanLinksSqlProvider;
import com.banry.pscm.persist.mapper.EngDivisionPlanSqlProvider;
import com.banry.pscm.service.schedule.EngDivisionPlan;
import com.banry.pscm.service.schedule.EngDivisionPlanKey;
import com.banry.pscm.service.schedule.EngDivisionPlanLinks;

public interface EngDivisionPlanMapper {

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eng_division_plan
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @Delete({
        "delete from eng_division_plan",
        "where division_sn_code = #{divisionSnCode,jdbcType=VARCHAR}",
          "and div_version = #{divVersion,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(EngDivisionPlanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eng_division_plan
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @Insert({
        "insert into eng_division_plan (division_sn_code, div_version, ",
        "start_date, end_date, pre_jobs, ",
        "version_date, version_man_code)",
        "values (#{divisionSnCode,jdbcType=VARCHAR}, #{divVersion,jdbcType=VARCHAR}, ",
        "#{startDate,jdbcType=DATE}, #{endDate,jdbcType=DATE}, #{preJobs,jdbcType=VARCHAR}, ",
        "#{versionDate,jdbcType=DATE}, #{versionManCode,jdbcType=VARCHAR})"
    })
    int insert(EngDivisionPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eng_division_plan
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @InsertProvider(type=EngDivisionPlanSqlProvider.class, method="insertSelective")
    int insertSelective(EngDivisionPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eng_division_plan
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @Select({
        "select",
        "division_sn_code, div_version, start_date, end_date, pre_jobs, version_date, ",
        "version_man_code",
        "from eng_division_plan",
        "where division_sn_code = #{divisionSnCode,jdbcType=VARCHAR}",
          "and div_version = #{divVersion,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="division_sn_code", property="divisionSnCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="div_version", property="divVersion", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="start_date", property="startDate", jdbcType=JdbcType.DATE),
        @Result(column="end_date", property="endDate", jdbcType=JdbcType.DATE),
        @Result(column="pre_jobs", property="preJobs", jdbcType=JdbcType.VARCHAR),
        @Result(column="version_date", property="versionDate", jdbcType=JdbcType.DATE),
        @Result(column="version_man_code", property="versionManCode", jdbcType=JdbcType.VARCHAR)
    })
    EngDivisionPlan selectByPrimaryKey(EngDivisionPlanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eng_division_plan
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @UpdateProvider(type=EngDivisionPlanSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EngDivisionPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eng_division_plan
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @Update({
        "update eng_division_plan",
        "set start_date = #{startDate,jdbcType=DATE},",
          "end_date = #{endDate,jdbcType=DATE},",
          "pre_jobs = #{preJobs,jdbcType=VARCHAR},",
          "version_date = #{versionDate,jdbcType=DATE},",
          "version_man_code = #{versionManCode,jdbcType=VARCHAR}",
        "where division_sn_code = #{divisionSnCode,jdbcType=VARCHAR}",
          "and div_version = #{divVersion,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(EngDivisionPlan record);

	@SelectProvider(type = EngDivisionPlanSqlProvider.class, method = "selectBySqlWhere")
	List<EngDivisionPlan> selectBySqlWhere(String sqlWhere);
}