package com.banry.pscm.persist.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.banry.pscm.persist.mapper.EngDivFinishRateSqlProvider;
import com.banry.pscm.service.schedule.EngDivFinishRate;
import com.banry.pscm.service.schedule.EngDivFinishRateKey;

public interface EngDivFinishRateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table eng_div_finish_rate
	 * @mbg.generated  Fri Jun 15 08:39:50 CST 2018
	 */
	@Delete({ "delete from eng_div_finish_rate", "where division_sn_code = #{divisionSnCode,jdbcType=VARCHAR}",
			"and work_date = #{workDate,jdbcType=DATE}" })
	int deleteByPrimaryKey(EngDivFinishRateKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table eng_div_finish_rate
	 * @mbg.generated  Fri Jun 15 08:39:50 CST 2018
	 */
	@Insert({ "insert into eng_div_finish_rate (division_sn_code, work_date, ", "finish_number, finish_where, ",
			"finish_attach, description)", "values (#{divisionSnCode,jdbcType=VARCHAR}, #{workDate,jdbcType=DATE}, ",
			"#{finishNumber,jdbcType=DOUBLE}, #{finishWhere,jdbcType=VARCHAR}, ",
			"#{finishAttach,jdbcType=VARCHAR}, #{description,jdbcType=LONGVARCHAR})" })
	int insert(EngDivFinishRate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table eng_div_finish_rate
	 * @mbg.generated  Fri Jun 15 08:39:50 CST 2018
	 */
	@InsertProvider(type = EngDivFinishRateSqlProvider.class, method = "insertSelective")
	int insertSelective(EngDivFinishRate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table eng_div_finish_rate
	 * @mbg.generated  Fri Jun 15 08:39:50 CST 2018
	 */
	@Select({ "select", "division_sn_code, work_date, finish_number, finish_where, finish_attach, description",
			"from eng_div_finish_rate", "where division_sn_code = #{divisionSnCode,jdbcType=VARCHAR}",
			"and work_date = #{workDate,jdbcType=DATE}" })
	@Results({
			@Result(column = "division_sn_code", property = "divisionSnCode", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "work_date", property = "workDate", jdbcType = JdbcType.DATE, id = true),
			@Result(column = "finish_number", property = "finishNumber", jdbcType = JdbcType.DOUBLE),
			@Result(column = "finish_where", property = "finishWhere", jdbcType = JdbcType.VARCHAR),
			@Result(column = "finish_attach", property = "finishAttach", jdbcType = JdbcType.VARCHAR),
			@Result(column = "description", property = "description", jdbcType = JdbcType.LONGVARCHAR) })
	EngDivFinishRate selectByPrimaryKey(EngDivFinishRateKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table eng_div_finish_rate
	 * @mbg.generated  Fri Jun 15 08:39:50 CST 2018
	 */
	@UpdateProvider(type = EngDivFinishRateSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(EngDivFinishRate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table eng_div_finish_rate
	 * @mbg.generated  Fri Jun 15 08:39:50 CST 2018
	 */
	@Update({ "update eng_div_finish_rate", "set finish_number = #{finishNumber,jdbcType=DOUBLE},",
			"finish_where = #{finishWhere,jdbcType=VARCHAR},", "finish_attach = #{finishAttach,jdbcType=VARCHAR},",
			"description = #{description,jdbcType=LONGVARCHAR}",
			"where division_sn_code = #{divisionSnCode,jdbcType=VARCHAR}",
			"and work_date = #{workDate,jdbcType=DATE}" })
	int updateByPrimaryKeyWithBLOBs(EngDivFinishRate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table eng_div_finish_rate
	 * @mbg.generated  Fri Jun 15 08:39:50 CST 2018
	 */
	@Update({ "update eng_div_finish_rate", "set finish_number = #{finishNumber,jdbcType=DOUBLE},",
			"finish_where = #{finishWhere,jdbcType=VARCHAR},", "finish_attach = #{finishAttach,jdbcType=VARCHAR}",
			"where division_sn_code = #{divisionSnCode,jdbcType=VARCHAR}",
			"and work_date = #{workDate,jdbcType=DATE}" })
	int updateByPrimaryKey(EngDivFinishRate record);
	
	@Select({ "select", "division_sn_code, sum(finish_number) finish_number", "from eng_div_finish_rate",
			"where division_sn_code = #{divsncode,jdbcType=VARCHAR}"})
	@Results({ @Result(column = "division_sn_code", property = "divisionSnCode", jdbcType = JdbcType.VARCHAR, id = true),
		@Result(column = "finish_number", property = "finishNumber", jdbcType = JdbcType.DOUBLE)})
	EngDivFinishRate sumFinishNumberByDivSnCode(String divCode);

	
	@SelectProvider(type = EngDivFinishRateSqlProvider.class, method = "selectBySqlWhere")
	List<EngDivFinishRate> selectBySqlWhere(String sqlWhere);
}