package com.banry.pscm.persist.dao;

import com.banry.pscm.persist.mapper.LaborSqlProvider;
import com.banry.pscm.service.labour.Labor;
import com.banry.pscm.service.labour.LaborWithBLOBs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface LaborMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor
     *
     * @mbggenerated
     */
    @Delete({
        "delete from labor",
        "where id_number = #{idNumber,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String idNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor
     *
     * @mbggenerated
     */
    @Insert({
        "insert into labor (id_number, name, ",
        "sex, birthday, education_degree, ",
        "height, weigh, worker_type, ",
        "career_year, address, ",
        "status, id_photo, ",
        "remark, trained_history, ",
        "profess_qualify)",
        "values (#{idNumber,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{sex,jdbcType=VARCHAR}, #{birthday,jdbcType=DATE}, #{educationDegree,jdbcType=INTEGER}, ",
        "#{height,jdbcType=INTEGER}, #{weigh,jdbcType=INTEGER}, #{workerType,jdbcType=VARCHAR}, ",
        "#{careerYear,jdbcType=INTEGER}, #{address,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=INTEGER}, #{idPhoto,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR}, #{trainedHistory,jdbcType=LONGVARCHAR}, ",
        "#{professQualify,jdbcType=LONGVARCHAR})"
    })
    int insert(LaborWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor
     *
     * @mbggenerated
     */
    @InsertProvider(type= LaborSqlProvider.class, method="insertSelective")
    int insertSelective(LaborWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id_number, name, sex, birthday, education_degree, height, weigh, worker_type, ",
        "career_year, address, status, id_photo, remark, trained_history, profess_qualify",
        "from labor",
        "where id_number = #{idNumber,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id_number", property="idNumber", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="sex", property="sex", jdbcType=JdbcType.VARCHAR),
        @Result(column="birthday", property="birthday", jdbcType=JdbcType.DATE),
        @Result(column="education_degree", property="educationDegree", jdbcType=JdbcType.INTEGER),
        @Result(column="height", property="height", jdbcType=JdbcType.INTEGER),
        @Result(column="weigh", property="weigh", jdbcType=JdbcType.INTEGER),
        @Result(column="worker_type", property="workerType", jdbcType=JdbcType.VARCHAR),
        @Result(column="career_year", property="careerYear", jdbcType=JdbcType.INTEGER),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="id_photo", property="idPhoto", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="trained_history", property="trainedHistory", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="profess_qualify", property="professQualify", jdbcType=JdbcType.LONGVARCHAR)
    })
    LaborWithBLOBs selectByPrimaryKey(String idNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor
     *
     * @mbggenerated
     */
    @UpdateProvider(type=LaborSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(LaborWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor
     *
     * @mbggenerated
     */
    @Update({
        "update labor",
        "set name = #{name,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=VARCHAR},",
          "birthday = #{birthday,jdbcType=DATE},",
          "education_degree = #{educationDegree,jdbcType=INTEGER},",
          "height = #{height,jdbcType=INTEGER},",
          "weigh = #{weigh,jdbcType=INTEGER},",
          "worker_type = #{workerType,jdbcType=VARCHAR},",
          "career_year = #{careerYear,jdbcType=INTEGER},",
          "address = #{address,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "id_photo = #{idPhoto,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "trained_history = #{trainedHistory,jdbcType=LONGVARCHAR},",
          "profess_qualify = #{professQualify,jdbcType=LONGVARCHAR}",
        "where id_number = #{idNumber,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(LaborWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor
     *
     * @mbggenerated
     */
    @Update({
        "update labor",
        "set name = #{name,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=VARCHAR},",
          "birthday = #{birthday,jdbcType=DATE},",
          "education_degree = #{educationDegree,jdbcType=INTEGER},",
          "height = #{height,jdbcType=INTEGER},",
          "weigh = #{weigh,jdbcType=INTEGER},",
          "worker_type = #{workerType,jdbcType=VARCHAR},",
          "career_year = #{careerYear,jdbcType=INTEGER},",
          "address = #{address,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "id_photo = #{idPhoto,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id_number = #{idNumber,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Labor record);
}