package com.banry.pscm.persist.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.banry.pscm.persist.mapper.RelateEnterpriseSqlProvider;
import com.banry.pscm.service.account.RelateEnterprise;

public interface RelateEnterpriseMapper {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relate_enterprise
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @Delete({
        "delete from relate_enterprise",
        "where enterprise_code = #{enterpriseCode,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String enterpriseCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relate_enterprise
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @Insert({
        "insert into relate_enterprise (enterprise_code, name, ",
        "post_code, address, ",
        "telephone, link_man, ",
        "link_man_phone, relate_type)",
        "values (#{enterpriseCode,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{postCode,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{telephone,jdbcType=VARCHAR}, #{linkMan,jdbcType=VARCHAR}, ",
        "#{linkManPhone,jdbcType=VARCHAR}, #{relateType,jdbcType=VARCHAR})"
    })
    int insert(RelateEnterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relate_enterprise
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @InsertProvider(type=RelateEnterpriseSqlProvider.class, method="insertSelective")
    int insertSelective(RelateEnterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relate_enterprise
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @Select({
        "select",
        "enterprise_code, name, post_code, address, telephone, link_man, link_man_phone, ",
        "relate_type",
        "from relate_enterprise",
        "where enterprise_code = #{enterpriseCode,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="enterprise_code", property="enterpriseCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="post_code", property="postCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="telephone", property="telephone", jdbcType=JdbcType.VARCHAR),
        @Result(column="link_man", property="linkMan", jdbcType=JdbcType.VARCHAR),
        @Result(column="link_man_phone", property="linkManPhone", jdbcType=JdbcType.VARCHAR),
        @Result(column="relate_type", property="relateType", jdbcType=JdbcType.VARCHAR)
    })
    RelateEnterprise selectByPrimaryKey(String enterpriseCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relate_enterprise
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @UpdateProvider(type=RelateEnterpriseSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(RelateEnterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relate_enterprise
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @Update({
        "update relate_enterprise",
        "set name = #{name,jdbcType=VARCHAR},",
          "post_code = #{postCode,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "telephone = #{telephone,jdbcType=VARCHAR},",
          "link_man = #{linkMan,jdbcType=VARCHAR},",
          "link_man_phone = #{linkManPhone,jdbcType=VARCHAR},",
          "relate_type = #{relateType,jdbcType=VARCHAR}",
        "where enterprise_code = #{enterpriseCode,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(RelateEnterprise record);
    
    @Select({
    	"select",
        "enterprise_code, name, post_code, address, telephone, link_man, link_man_phone, ",
        "relate_type",
        "from relate_enterprise"
    })
    @Results({
        @Result(column="enterprise_code", property="enterpriseCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="post_code", property="postCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="telephone", property="telephone", jdbcType=JdbcType.VARCHAR),
        @Result(column="link_man", property="linkMan", jdbcType=JdbcType.VARCHAR),
        @Result(column="link_man_phone", property="linkManPhone", jdbcType=JdbcType.VARCHAR),
        @Result(column="relate_type", property="relateType", jdbcType=JdbcType.VARCHAR)
    })
    List<RelateEnterprise> selectAll();
}