package com.banry.pscm.persist.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;

import com.banry.pscm.persist.mapper.TenderPlanSQLBuilder;
import com.banry.pscm.service.tender.ReleaseTarget;

public interface ReleaseTargetMapper {
	
	@SelectProvider(type = TenderPlanSQLBuilder.class,method = "findTargetBySqlWhere")
	List<ReleaseTarget> findTargetBySqlWhere(String sqlWhere);
	
	@Select({"select * from release_target where tender_plan_code = #{tenderPlanCode,jdbcType=VARCHAR}"})
	@Results({@Result(column = "target_code", property = "targetCode", jdbcType = JdbcType.VARCHAR, id = true),
		@Result(column = "eng_code", property = "engCode", jdbcType = JdbcType.VARCHAR),
		@Result(column = "tender_plan_code", property = "tenderPlanCode", jdbcType = JdbcType.VARCHAR),
		@Result(column = "target_name", property = "targetName", jdbcType = JdbcType.VARCHAR),
		@Result(column = "address", property = "address", jdbcType = JdbcType.VARCHAR),
		@Result(column = "release_date", property = "releaseDate", jdbcType = JdbcType.DATE),
		@Result(column = "start_date", property = "startDate", jdbcType = JdbcType.DATE),
		@Result(column = "end_date", property = "endDate", jdbcType = JdbcType.DATE)})
	List<ReleaseTarget> findReleaseByTenderPlanCode(String tenderPlanCode);
	
	@Select({"select * from release_target"})
	@Results({@Result(column = "target_code", property = "targetCode", jdbcType = JdbcType.VARCHAR, id = true),
		@Result(column = "eng_code", property = "engCode", jdbcType = JdbcType.VARCHAR),
		@Result(column = "tender_plan_code", property = "tenderPlanCode", jdbcType = JdbcType.VARCHAR),
		@Result(column = "target_name", property = "targetName", jdbcType = JdbcType.VARCHAR),
		@Result(column = "address", property = "address", jdbcType = JdbcType.VARCHAR),
		@Result(column = "release_date", property = "releaseDate", jdbcType = JdbcType.DATE),
		@Result(column = "start_date", property = "startDate", jdbcType = JdbcType.DATE),
		@Result(column = "end_date", property = "endDate", jdbcType = JdbcType.DATE)})
	List<ReleaseTarget> findAllReleaseTarget();
	
	@Delete({ "delete from release_target", "where tender_plan_code = #{tenderPlanCode,jdbcType=VARCHAR}" })
	int deleteByTenderPlanCode(String tenderPlanCode);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_target
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    int deleteByPrimaryKey(String targetCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_target
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    int insert(ReleaseTarget record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_target
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    int insertSelective(ReleaseTarget record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_target
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    ReleaseTarget selectByPrimaryKey(String targetCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_target
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    int updateByPrimaryKeySelective(ReleaseTarget record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_target
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    int updateByPrimaryKey(ReleaseTarget record);
}