package com.banry.pscm.persist.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.banry.pscm.persist.mapper.RoleSqlProvider;
import com.banry.pscm.service.account.Role;
import com.banry.pscm.service.account.RoleKey;

public interface RoleMapper {

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @Delete({
        "delete from role",
        "where role_code = #{roleCode,jdbcType=VARCHAR}",
          "and tenant_code = #{tenantCode,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(RoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @Insert({
        "insert into role (role_code, tenant_code, ",
        "dept_code, name, ",
        "create_user, create_date, ",
        "status)",
        "values (#{roleCode,jdbcType=VARCHAR}, #{tenantCode,jdbcType=VARCHAR}, ",
        "#{deptCode,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{createUser,jdbcType=VARCHAR}, #{createDate,jdbcType=TIMESTAMP}, ",
        "#{status,jdbcType=INTEGER})"
    })
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @InsertProvider(type=RoleSqlProvider.class, method="insertSelective")
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @Select({
        "select",
        "role_code, tenant_code, dept_code, name, create_user, create_date, status",
        "from role",
        "where role_code = #{roleCode,jdbcType=VARCHAR}",
          "and tenant_code = #{tenantCode,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="role_code", property="roleCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="tenant_code", property="tenantCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="dept_code", property="deptCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER)
    })
    Role selectByPrimaryKey(RoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @UpdateProvider(type=RoleSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @Update({
        "update role",
        "set dept_code = #{deptCode,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "create_user = #{createUser,jdbcType=VARCHAR},",
          "create_date = #{createDate,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=INTEGER}",
        "where role_code = #{roleCode,jdbcType=VARCHAR}",
          "and tenant_code = #{tenantCode,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Role record);

	@SelectProvider(type = RoleSqlProvider.class, method = "selectRoleByUserCode")
	List<Role> selectRoleByUserCode(@Param("tenantCode") String tenantCode, @Param("userCode") String userCode);
	
	@SelectProvider(type = RoleSqlProvider.class, method = "selectBySqlWhere")
	List<Role> selectBySqlWhere(String sqlWhere);
	
	@SelectProvider(type = RoleSqlProvider.class, method = "selectEngDivByUserCode")
	List<String> selectEngDivByUserCode(@Param("tenantAccount") String tenantAccount, @Param("userCode") String userCode);
}