package com.banry.pscm.persist.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.banry.pscm.persist.mapper.SubDivWorkQuotaSqlProvider;
import com.banry.pscm.service.schedule.SubDivWorkQuota;

public interface SubDivWorkQuotaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_div_work_quota
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @Delete({
        "delete from sub_div_work_quota",
        "where res_code = #{resCode,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String resCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_div_work_quota
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @Insert({
        "insert into sub_div_work_quota (res_code, division_sn_code, ",
        "resources_type, res_name, ",
        "res_type_level, unit, ",
        "bid_map_quan, raw_cons_map_quan, ",
        "cons_map_sum_vary_quan, loss_rate, ",
        "comp_unit_price, save_excess_rate)",
        "values (#{resCode,jdbcType=VARCHAR}, #{divisionSnCode,jdbcType=VARCHAR}, ",
        "#{resourcesType,jdbcType=VARCHAR}, #{resName,jdbcType=VARCHAR}, ",
        "#{resTypeLevel,jdbcType=VARCHAR}, #{unit,jdbcType=VARCHAR}, ",
        "#{bidMapQuan,jdbcType=DOUBLE}, #{rawConsMapQuan,jdbcType=DOUBLE}, ",
        "#{consMapSumVaryQuan,jdbcType=DOUBLE}, #{lossRate,jdbcType=DOUBLE}, ",
        "#{compUnitPrice,jdbcType=DOUBLE}, #{saveExcessRate,jdbcType=DOUBLE})"
    })
    int insert(SubDivWorkQuota record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_div_work_quota
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @InsertProvider(type=SubDivWorkQuotaSqlProvider.class, method="insertSelective")
    int insertSelective(SubDivWorkQuota record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_div_work_quota
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @Select({
        "select",
        "res_code, division_sn_code, resources_type, res_name, res_type_level, unit, ",
        "bid_map_quan, raw_cons_map_quan, cons_map_sum_vary_quan, loss_rate, comp_unit_price, ",
        "save_excess_rate",
        "from sub_div_work_quota",
        "where res_code = #{resCode,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="res_code", property="resCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="division_sn_code", property="divisionSnCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="resources_type", property="resourcesType", jdbcType=JdbcType.VARCHAR),
        @Result(column="res_name", property="resName", jdbcType=JdbcType.VARCHAR),
        @Result(column="res_type_level", property="resTypeLevel", jdbcType=JdbcType.VARCHAR),
        @Result(column="unit", property="unit", jdbcType=JdbcType.VARCHAR),
        @Result(column="bid_map_quan", property="bidMapQuan", jdbcType=JdbcType.DOUBLE),
        @Result(column="raw_cons_map_quan", property="rawConsMapQuan", jdbcType=JdbcType.DOUBLE),
        @Result(column="cons_map_sum_vary_quan", property="consMapSumVaryQuan", jdbcType=JdbcType.DOUBLE),
        @Result(column="loss_rate", property="lossRate", jdbcType=JdbcType.DOUBLE),
        @Result(column="comp_unit_price", property="compUnitPrice", jdbcType=JdbcType.DOUBLE),
        @Result(column="save_excess_rate", property="saveExcessRate", jdbcType=JdbcType.DOUBLE)
    })
    SubDivWorkQuota selectByPrimaryKey(String resCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_div_work_quota
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @UpdateProvider(type=SubDivWorkQuotaSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SubDivWorkQuota record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_div_work_quota
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    @Update({
        "update sub_div_work_quota",
        "set division_sn_code = #{divisionSnCode,jdbcType=VARCHAR},",
          "resources_type = #{resourcesType,jdbcType=VARCHAR},",
          "res_name = #{resName,jdbcType=VARCHAR},",
          "res_type_level = #{resTypeLevel,jdbcType=VARCHAR},",
          "unit = #{unit,jdbcType=VARCHAR},",
          "bid_map_quan = #{bidMapQuan,jdbcType=DOUBLE},",
          "raw_cons_map_quan = #{rawConsMapQuan,jdbcType=DOUBLE},",
          "cons_map_sum_vary_quan = #{consMapSumVaryQuan,jdbcType=DOUBLE},",
          "loss_rate = #{lossRate,jdbcType=DOUBLE},",
          "comp_unit_price = #{compUnitPrice,jdbcType=DOUBLE},",
          "save_excess_rate = #{saveExcessRate,jdbcType=DOUBLE}",
        "where res_code = #{resCode,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SubDivWorkQuota record);
    
    /**
	 * @param unit 资源单位
	 * @return
	 */
	@Select({"select ",
		"res_code,division_sn_code,resources_type,res_name,res_type_level,unit," + 
		"bid_map_quan,raw_cons_map_quan,cons_map_sum_vary_quan,loss_rate,comp_unit_price,save_excess_rate ",
    	"from sub_div_work_quota ",
    	"where unit = #{unit,jdbcType=VARCHAR} "})
    @Results(id="BaseSubDivWorkQuota",value = {@Result(column = "res_code", property = "resCode", jdbcType = JdbcType.VARCHAR, id = true),
		@Result(column = "division_sn_code", property = "divisionSnCode", jdbcType = JdbcType.VARCHAR),
		@Result(column = "resources_type", property = "resourcesType", jdbcType = JdbcType.VARCHAR),
		@Result(column = "res_name", property = "resName", jdbcType = JdbcType.VARCHAR),
		@Result(column = "res_type_level", property = "resTypeLevel", jdbcType = JdbcType.VARCHAR),
		@Result(column = "unit", property = "unit", jdbcType = JdbcType.VARCHAR),
		@Result(column = "bid_map_quan", property = "bidMapQuan", jdbcType = JdbcType.DOUBLE),
		@Result(column = "raw_cons_map_quan", property = "rawConsMapQuan", jdbcType = JdbcType.DOUBLE),
		@Result(column = "cons_map_sum_vary_quan", property = "consMapSumVaryQuan", jdbcType = JdbcType.DOUBLE),
		@Result(column = "loss_rate", property = "lossRate", jdbcType = JdbcType.DOUBLE),
		@Result(column = "comp_unit_price", property = "compUnitPrice", jdbcType = JdbcType.DOUBLE),
		@Result(column = "save_excess_rate", property = "saveExcessRate", jdbcType = JdbcType.DOUBLE) })
	List<SubDivWorkQuota> findSubDivWorkQuotaByUnit(String unit);
	
	/**
	 * @param divisionSnCode
	 * @return
	 */
	@Select({"select ",
		"res_code,division_sn_code,resources_type,res_name,res_type_level,unit," + 
		"bid_map_quan,raw_cons_map_quan,cons_map_sum_vary_quan,loss_rate,comp_unit_price,save_excess_rate ",
    	"from sub_div_work_quota ",
    	"where division_sn_code = #{divisionSnCode,jdbcType=VARCHAR} "})
	@ResultMap("BaseSubDivWorkQuota")
	List<SubDivWorkQuota> findSubDivWorkQuotaByDivisionSnCode(String divisionSnCode);

	/**
	 * @param resourcesType 资源类型：人工�?�材料�?�机�??
	 * @return
	 */
	@Select({"select ",
		"res_code,division_sn_code,resources_type,res_name,res_type_level,unit," + 
		"bid_map_quan,raw_cons_map_quan,cons_map_sum_vary_quan,loss_rate,comp_unit_price,save_excess_rate ",
    	"from sub_div_work_quota ",
    	"where resources_type = #{resourcesType,jdbcType=VARCHAR} "})
	@ResultMap("BaseSubDivWorkQuota")
	List<SubDivWorkQuota> findSubDivWorkQuotaByResourcesType(String resourcesType);

	/**
	 * @param resName
	 * @return
	 */
	@Select({"select ",
		"res_code,division_sn_code,resources_type,res_name,res_type_level,unit," + 
		"bid_map_quan,raw_cons_map_quan,cons_map_sum_vary_quan,loss_rate,comp_unit_price,save_excess_rate ",
    	"from sub_div_work_quota ",
    	"where res_name like concat('%',#{resName,jdbcType=VARCHAR},'%') "})
	@ResultMap("BaseSubDivWorkQuota")
	List<SubDivWorkQuota> findSubDivWorkQuotaByResName(String resName);

	/**
	 * @return
	 */
	@Select({"select ",
		"res_code,division_sn_code,resources_type,res_name,res_type_level,unit," + 
		"bid_map_quan,raw_cons_map_quan,cons_map_sum_vary_quan,loss_rate,comp_unit_price,save_excess_rate ",
    	"from sub_div_work_quota "})
	@ResultMap("BaseSubDivWorkQuota")
	List<SubDivWorkQuota> findAllSubDivWorkQuota();

	/**
	 * 删除定额数据表（sub_div_work_quota）中division_sn_code属性为传入的divisionsncode的信�?
	 * @param divisionsncode
	 * @return
	 */
	@Delete("delete from sub_div_work_quota where division_sn_code = #{divisionsncode}")
	int deleteSubDivWorkQuotaByDivisionSnCode(String divisionsncode);

	@Select({"select status from sub_div_work_bill bill,sub_div_work_quota quota ",
		"where quota.res_code = #{rescode,jdbcType=VARCHAR} and quota.division_sn_code = bill.division_sn_code;"})
	int findSubDivWorkBillStatus(String rescode);
	
}