package com.banry.pscm.persist.dao;

import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import com.banry.pscm.persist.mapper.TenderPlanSQLBuilder;
import com.banry.pscm.service.tender.Supplier;

public interface SupplierMapper {

	@SelectProvider(type = TenderPlanSQLBuilder.class,method = "findSupplierBySqlWhere")
	List<Supplier> findSupplierBySqlWhere(String sqlWhere);

	@Select({"select * from supplier"})
	@Results(id = "Supplier_Base_Map",
            value = {@Result(column = "supplier_credit_code", property = "supplierCreditCode", jdbcType = JdbcType.VARCHAR, id = true),
		@Result(column = "supplier_name", property = "supplierName", jdbcType = JdbcType.VARCHAR),
		@Result(column = "contact_man", property = "contactMan", jdbcType = JdbcType.VARCHAR),
		@Result(column = "contact_tel", property = "contactTel", jdbcType = JdbcType.VARCHAR),
		@Result(column = "refereer", property = "refereer", jdbcType = JdbcType.VARCHAR),
		@Result(column = "achievements", property = "achievements", jdbcType = JdbcType.VARCHAR),
		@Result(column = "legal_person", property = "legalPerson", jdbcType = JdbcType.VARCHAR),
		@Result(column = "qualification_level", property = "qualificationLevel", jdbcType = JdbcType.VARCHAR),
		@Result(column = "supplier_tel", property = "supplierTel", jdbcType = JdbcType.VARCHAR),
		@Result(column = "mail_add", property = "mailAdd", jdbcType = JdbcType.VARCHAR),
		@Result(column = "supplier_category", property = "supplierCategory", jdbcType = JdbcType.INTEGER),
		@Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER),
		@Result(column = "remark", property = "remark", jdbcType = JdbcType.VARCHAR)})
	public List<Supplier> findAllSupplier();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    int deleteByPrimaryKey(String supplierCreditCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    int insert(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    int insertSelective(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    Supplier selectByPrimaryKey(String supplierCreditCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    int updateByPrimaryKeySelective(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    int updateByPrimaryKey(Supplier record);

    Supplier selectByUserCodeOrTel(String userCodeOrTel);

    @Select({
            "SELECT",
            "	* ",
            "FROM",
            "	supplier ",
            "WHERE",
            "	supplier_credit_code IN ( SELECT DISTINCT supplier_credit_code ",
                    "FROM sub_div_work_bill WHERE tender_result_code = #{tenderResultCode, jdbcType = VARCHAR} )",
    })
    @ResultMap("Supplier_Base_Map")
    List<Supplier> findByTenderResultCode(@Param("tenderResultCode") String tenderResultCode);
}