package com.banry.pscm.persist.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;

import com.banry.pscm.persist.mapper.TenderPlanSQLBuilder;
import com.banry.pscm.service.tender.SupplierBidItemRate;

public interface SupplierBidItemRateMapper {
	
	@SelectProvider(type = TenderPlanSQLBuilder.class,method = "findRateBySqlWhere")
	List<SupplierBidItemRate> findRateBySqlWhere(String sqlWhere);
	
	@Select({"select * from supplier_bid_item_rate where division_sn_code = #{divisionSnCode,jdbcType=VARCHAR}"})
	@Results({@Result(column = "item_bid_code", property = "itemBidCode", jdbcType = JdbcType.VARCHAR, id = true),
//		@Result(column = "division_sn_code", property = "divisionSnCode", jdbcType = JdbcType.VARCHAR),
		@Result(column = "supplier_credit_code", property = "supplierCreditCode", jdbcType = JdbcType.VARCHAR),
		@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
		@Result(column = "first_bid_unit_rate", property = "firstBidUnitRate", jdbcType = JdbcType.DOUBLE),
		@Result(column = "end_bid_unit_rate", property = "endBidUnitRate", jdbcType = JdbcType.DOUBLE)})
	SupplierBidItemRate findSupplierBidItemRateByDivCode(String divisionSnCode);
	
	@Select({"select * from supplier_bid_item_rate"})
	@Results({@Result(column = "item_bid_code", property = "itemBidCode", jdbcType = JdbcType.VARCHAR, id = true),
//		@Result(column = "division_sn_code", property = "divisionSnCode", jdbcType = JdbcType.VARCHAR),
		@Result(column = "supplier_credit_code", property = "supplierCreditCode", jdbcType = JdbcType.VARCHAR),
		@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
		@Result(column = "first_bid_unit_rate", property = "firstBidUnitRate", jdbcType = JdbcType.DOUBLE),
		@Result(column = "end_bid_unit_rate", property = "endBidUnitRate", jdbcType = JdbcType.DOUBLE)})
	List<SupplierBidItemRate> findAllSupplierBidItemRate();
	
	@Select({"select * from supplier_bid_item_rate where division_sn_code = #{divisionSnCode,jdbcType=VARCHAR}",
		" and supplier_credit_code = #{supplierCreditCode,jdbcType=VARCHAR}"})
	@Results({@Result(column = "item_bid_code", property = "itemBidCode", jdbcType = JdbcType.VARCHAR, id = true),
//		@Result(column = "division_sn_code", property = "divisionSnCode", jdbcType = JdbcType.VARCHAR),
		@Result(column = "supplier_credit_code", property = "supplierCreditCode", jdbcType = JdbcType.VARCHAR),
		@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
		@Result(column = "first_bid_unit_rate", property = "firstBidUnitRate", jdbcType = JdbcType.DOUBLE),
		@Result(column = "end_bid_unit_rate", property = "endBidUnitRate", jdbcType = JdbcType.DOUBLE)})
	SupplierBidItemRate findSupplierBidItemRateByDivCodeAndSupplierCode(@Param("divisionSnCode") String divisionSnCode, @Param("supplierCreditCode") String supplierCreditCode);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_bid_item_rate
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    int deleteByPrimaryKey(String itemBidCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_bid_item_rate
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    int insert(SupplierBidItemRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_bid_item_rate
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    int insertSelective(SupplierBidItemRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_bid_item_rate
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    SupplierBidItemRate selectByPrimaryKey(String itemBidCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_bid_item_rate
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    int updateByPrimaryKeySelective(SupplierBidItemRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_bid_item_rate
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    int updateByPrimaryKey(SupplierBidItemRate record);
    
    List<SupplierBidItemRate> getSupBidItemRateByTpCodeAndSupCode(Map map);
    
    List<SupplierBidItemRate> getMoveInOrChangeSupplierSupBidItemRateByChangeCode(Map map);
    
    List<SupplierBidItemRate> findSupplierBidItemRateByTenderPlanCode(String tenderPlanCode);
}