package com.banry.pscm.persist.dao;

import java.util.List;
import java.util.Map;

import com.banry.pscm.service.tender.SupplierBidRate;

public interface SupplierBidRateMapper {
	
	List<SupplierBidRate> findSupplierBidRateByResultCode(Map map);
	
	List<SupplierBidRate> findAllSupplierBidRate(String parentTenantAccount);
	
	SupplierBidRate findSupplierIsExists(SupplierBidRate record);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_bid_rate
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    int deleteByPrimaryKey(String itemBidCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_bid_rate
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    int insert(SupplierBidRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_bid_rate
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    int insertSelective(SupplierBidRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_bid_rate
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    SupplierBidRate selectByPrimaryKey(String itemBidCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_bid_rate
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    int updateByPrimaryKeySelective(SupplierBidRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_bid_rate
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    int updateByPrimaryKey(SupplierBidRate record);
}