package com.banry.pscm.persist.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.banry.pscm.persist.mapper.SysDeptsSqlProvider;
import com.banry.pscm.service.account.SysDepts;
import com.banry.pscm.service.account.SysDeptsKey;

public interface SysDeptsMapper {

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_depts
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @Delete({
        "delete from sys_depts",
        "where dept_code = #{deptCode,jdbcType=VARCHAR}",
          "and tenant_code = #{tenantCode,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(SysDeptsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_depts
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @Insert({
        "insert into sys_depts (dept_code, tenant_code, ",
        "enterprise_code, dept_name, ",
        "dept_addre, dept_organize_date, ",
        "telephone, mail_address, ",
        "link_man_code)",
        "values (#{deptCode,jdbcType=VARCHAR}, #{tenantCode,jdbcType=VARCHAR}, ",
        "#{enterpriseCode,jdbcType=VARCHAR}, #{deptName,jdbcType=VARCHAR}, ",
        "#{deptAddre,jdbcType=VARCHAR}, #{deptOrganizeDate,jdbcType=DATE}, ",
        "#{telephone,jdbcType=VARCHAR}, #{mailAddress,jdbcType=VARCHAR}, ",
        "#{linkManCode,jdbcType=VARCHAR})"
    })
    int insert(SysDepts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_depts
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @InsertProvider(type=SysDeptsSqlProvider.class, method="insertSelective")
    int insertSelective(SysDepts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_depts
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @Select({
        "select",
        "dept_code, tenant_code, enterprise_code, dept_name, dept_addre, dept_organize_date, ",
        "telephone, mail_address, link_man_code",
        "from sys_depts",
        "where dept_code = #{deptCode,jdbcType=VARCHAR}",
          "and tenant_code = #{tenantCode,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="dept_code", property="deptCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="tenant_code", property="tenantCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="enterprise_code", property="enterpriseCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="dept_name", property="deptName", jdbcType=JdbcType.VARCHAR),
        @Result(column="dept_addre", property="deptAddre", jdbcType=JdbcType.VARCHAR),
        @Result(column="dept_organize_date", property="deptOrganizeDate", jdbcType=JdbcType.DATE),
        @Result(column="telephone", property="telephone", jdbcType=JdbcType.VARCHAR),
        @Result(column="mail_address", property="mailAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="link_man_code", property="linkManCode", jdbcType=JdbcType.VARCHAR)
    })
    SysDepts selectByPrimaryKey(SysDeptsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_depts
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @UpdateProvider(type=SysDeptsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SysDepts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_depts
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @Update({
        "update sys_depts",
        "set enterprise_code = #{enterpriseCode,jdbcType=VARCHAR},",
          "dept_name = #{deptName,jdbcType=VARCHAR},",
          "dept_addre = #{deptAddre,jdbcType=VARCHAR},",
          "dept_organize_date = #{deptOrganizeDate,jdbcType=DATE},",
          "telephone = #{telephone,jdbcType=VARCHAR},",
          "mail_address = #{mailAddress,jdbcType=VARCHAR},",
          "link_man_code = #{linkManCode,jdbcType=VARCHAR}",
        "where dept_code = #{deptCode,jdbcType=VARCHAR}",
          "and tenant_code = #{tenantCode,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SysDepts record);
	
	@Select({ "select", "dept_code, tenant_code, enterprise_code, dept_name, dept_addre, dept_organize_date, ",
        "telephone, mail_address, link_man_code", "from sys_depts",
		"where tenant_code = #{tenantCode,jdbcType=VARCHAR} or '' = #{tenantCode,jdbcType=VARCHAR}"})
	@Results({
        @Result(column="dept_code", property="deptCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="tenant_code", property="tenantCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="enterprise_code", property="enterpriseCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="dept_name", property="deptName", jdbcType=JdbcType.VARCHAR),
        @Result(column="dept_addre", property="deptAddre", jdbcType=JdbcType.VARCHAR),
        @Result(column="dept_organize_date", property="deptOrganizeDate", jdbcType=JdbcType.DATE),
        @Result(column="telephone", property="telephone", jdbcType=JdbcType.VARCHAR),
        @Result(column="mail_address", property="mailAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="link_man_code", property="linkManCode", jdbcType=JdbcType.VARCHAR)
    })
	List<SysDepts> selectAll(String tenantCode);

}