package com.banry.pscm.persist.dao;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.banry.pscm.persist.mapper.SysRolesResourcesSqlProvider;
import com.banry.pscm.service.account.SysRolesResources;

public interface SysRolesResourcesMapper {

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_resources
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @Delete({
        "delete from sys_roles_resources",
        "where role_resource_code = #{roleResourceCode,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String roleResourceCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_resources
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @Insert({
        "insert into sys_roles_resources (role_resource_code, role_code, ",
        "tenant_code, create_user, ",
        "create_date, status, ",
        "resource_code)",
        "values (#{roleResourceCode,jdbcType=VARCHAR}, #{roleCode,jdbcType=VARCHAR}, ",
        "#{tenantCode,jdbcType=VARCHAR}, #{createUser,jdbcType=VARCHAR}, ",
        "#{createDate,jdbcType=TIMESTAMP}, #{status,jdbcType=INTEGER}, ",
        "#{resourceCode,jdbcType=VARCHAR})"
    })
    int insert(SysRolesResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_resources
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @InsertProvider(type=SysRolesResourcesSqlProvider.class, method="insertSelective")
    int insertSelective(SysRolesResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_resources
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @Select({
        "select",
        "role_resource_code, role_code, tenant_code, create_user, create_date, status, ",
        "resource_code",
        "from sys_roles_resources",
        "where role_resource_code = #{roleResourceCode,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="role_resource_code", property="roleResourceCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="role_code", property="roleCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="tenant_code", property="tenantCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="resource_code", property="resourceCode", jdbcType=JdbcType.VARCHAR)
    })
    SysRolesResources selectByPrimaryKey(String roleResourceCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_resources
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @UpdateProvider(type=SysRolesResourcesSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SysRolesResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_resources
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    @Update({
        "update sys_roles_resources",
        "set role_code = #{roleCode,jdbcType=VARCHAR},",
          "tenant_code = #{tenantCode,jdbcType=VARCHAR},",
          "create_user = #{createUser,jdbcType=VARCHAR},",
          "create_date = #{createDate,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=INTEGER},",
          "resource_code = #{resourceCode,jdbcType=VARCHAR}",
        "where role_resource_code = #{roleResourceCode,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SysRolesResources record);
	
	@Delete({ "delete from sys_roles_resources", "where role_code = #{rolecode,jdbcType=VARCHAR} and tenant_code = #{tenantCode,jdbcType=VARCHAR}" })
	int deleteByRoleCode(@Param("rolecode") String rolecode, @Param("tenantCode") String tenantCode);
}