package com.banry.pscm.service.contract;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class SettleAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.settle_code
     *
     * @mbggenerated
     */
    private String settleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.down_contract_code
     *
     * @mbggenerated
     */
    private String downContractCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.settle_name
     *
     * @mbggenerated
     */
    private String settleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.settle_date
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date settleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.settle_type
     *
     * @mbggenerated
     */
    private Integer settleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.settlte_unit
     *
     * @mbggenerated
     */
    private String settleUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.cur_settle_amount
     *
     * @mbggenerated
     */
    private Double curSettleAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.settle_number
     *
     * @mbggenerated
     */
    private Integer settleNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.sum_settle_amount
     *
     * @mbggenerated
     */
    private Double sumSettleAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.eng_cal_status
     *
     * @mbggenerated
     */
    private Integer engCalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.eng_sum_status
     *
     * @mbggenerated
     */
    private Integer engSumStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.contract_in_settle_sum_status
     *
     * @mbggenerated
     */
    private Integer contractInSettleSumStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.eng_check_value_sum_status
     *
     * @mbggenerated
     */
    private Integer engCheckValueSumStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.cur_actual_pay_amount
     *
     * @mbggenerated
     */
    private Double curActualPayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.cur_payable_amount
     *
     * @mbggenerated
     */
    private Double curPayableAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.sum_surplus_amount
     *
     * @mbggenerated
     */
    private Double sumSurplusAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.sum_actual_pay_amount
     *
     * @mbggenerated
     */
    private Double sumActualPayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.sum_payable_amount
     *
     * @mbggenerated
     */
    private Double sumPayableAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.settle_contract
     *
     * @mbggenerated
     */
    private String settleContract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_account.settlte_attach
     *
     * @mbggenerated
     */
    private String settleAttach;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.settle_code
     *
     * @return the value of settle_account.settle_code
     *
     * @mbggenerated
     */
    public String getSettleCode() {
        return settleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.settle_code
     *
     * @param settleCode the value for settle_account.settle_code
     *
     * @mbggenerated
     */
    public void setSettleCode(String settleCode) {
        this.settleCode = settleCode == null ? null : settleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.down_contract_code
     *
     * @return the value of settle_account.down_contract_code
     *
     * @mbggenerated
     */
    public String getDownContractCode() {
        return downContractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.down_contract_code
     *
     * @param downContractCode the value for settle_account.down_contract_code
     *
     * @mbggenerated
     */
    public void setDownContractCode(String downContractCode) {
        this.downContractCode = downContractCode == null ? null : downContractCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.settle_name
     *
     * @return the value of settle_account.settle_name
     *
     * @mbggenerated
     */
    public String getSettleName() {
        return settleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.settle_name
     *
     * @param settleName the value for settle_account.settle_name
     *
     * @mbggenerated
     */
    public void setSettleName(String settleName) {
        this.settleName = settleName == null ? null : settleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.settle_date
     *
     * @return the value of settle_account.settle_date
     *
     * @mbggenerated
     */
    public Date getSettleDate() {
        return settleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.settle_date
     *
     * @param settleDate the value for settle_account.settle_date
     *
     * @mbggenerated
     */
    public void setSettleDate(Date settleDate) {
        this.settleDate = settleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.settle_type
     *
     * @return the value of settle_account.settle_type
     *
     * @mbggenerated
     */
    public Integer getSettleType() {
        return settleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.settle_type
     *
     * @param settleType the value for settle_account.settle_type
     *
     * @mbggenerated
     */
    public void setSettleType(Integer settleType) {
        this.settleType = settleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.settlte_unit
     *
     * @return the value of settle_account.settlte_unit
     *
     * @mbggenerated
     */
    public String getSettleUnit() {
        return settleUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.settlte_unit
     *
     * @param settleUnit the value for settle_account.settlte_unit
     *
     * @mbggenerated
     */
    public void setSettleUnit(String settleUnit) {
        this.settleUnit = settleUnit == null ? null : settleUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.cur_settle_amount
     *
     * @return the value of settle_account.cur_settle_amount
     *
     * @mbggenerated
     */
    public Double getCurSettleAmount() {
        return curSettleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.cur_settle_amount
     *
     * @param curSettleAmount the value for settle_account.cur_settle_amount
     *
     * @mbggenerated
     */
    public void setCurSettleAmount(Double curSettleAmount) {
        this.curSettleAmount = curSettleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.settle_number
     *
     * @return the value of settle_account.settle_number
     *
     * @mbggenerated
     */
    public Integer getSettleNumber() {
        return settleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.settle_number
     *
     * @param settleNumber the value for settle_account.settle_number
     *
     * @mbggenerated
     */
    public void setSettleNumber(Integer settleNumber) {
        this.settleNumber = settleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.sum_settle_amount
     *
     * @return the value of settle_account.sum_settle_amount
     *
     * @mbggenerated
     */
    public Double getSumSettleAmount() {
        return sumSettleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.sum_settle_amount
     *
     * @param sumSettleAmount the value for settle_account.sum_settle_amount
     *
     * @mbggenerated
     */
    public void setSumSettleAmount(Double sumSettleAmount) {
        this.sumSettleAmount = sumSettleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.eng_cal_status
     *
     * @return the value of settle_account.eng_cal_status
     *
     * @mbggenerated
     */
    public Integer getEngCalStatus() {
        return engCalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.eng_cal_status
     *
     * @param engCalStatus the value for settle_account.eng_cal_status
     *
     * @mbggenerated
     */
    public void setEngCalStatus(Integer engCalStatus) {
        this.engCalStatus = engCalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.eng_sum_status
     *
     * @return the value of settle_account.eng_sum_status
     *
     * @mbggenerated
     */
    public Integer getEngSumStatus() {
        return engSumStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.eng_sum_status
     *
     * @param engSumStatus the value for settle_account.eng_sum_status
     *
     * @mbggenerated
     */
    public void setEngSumStatus(Integer engSumStatus) {
        this.engSumStatus = engSumStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.contract_in_settle_sum_status
     *
     * @return the value of settle_account.contract_in_settle_sum_status
     *
     * @mbggenerated
     */
    public Integer getContractInSettleSumStatus() {
        return contractInSettleSumStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.contract_in_settle_sum_status
     *
     * @param contractInSettleSumStatus the value for settle_account.contract_in_settle_sum_status
     *
     * @mbggenerated
     */
    public void setContractInSettleSumStatus(Integer contractInSettleSumStatus) {
        this.contractInSettleSumStatus = contractInSettleSumStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.eng_check_value_sum_status
     *
     * @return the value of settle_account.eng_check_value_sum_status
     *
     * @mbggenerated
     */
    public Integer getEngCheckValueSumStatus() {
        return engCheckValueSumStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.eng_check_value_sum_status
     *
     * @param engCheckValueSumStatus the value for settle_account.eng_check_value_sum_status
     *
     * @mbggenerated
     */
    public void setEngCheckValueSumStatus(Integer engCheckValueSumStatus) {
        this.engCheckValueSumStatus = engCheckValueSumStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.status
     *
     * @return the value of settle_account.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.status
     *
     * @param status the value for settle_account.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.cur_actual_pay_amount
     *
     * @return the value of settle_account.cur_actual_pay_amount
     *
     * @mbggenerated
     */
    public Double getCurActualPayAmount() {
        return curActualPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.cur_actual_pay_amount
     *
     * @param curActualPayAmount the value for settle_account.cur_actual_pay_amount
     *
     * @mbggenerated
     */
    public void setCurActualPayAmount(Double curActualPayAmount) {
        this.curActualPayAmount = curActualPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.cur_payable_amount
     *
     * @return the value of settle_account.cur_payable_amount
     *
     * @mbggenerated
     */
    public Double getCurPayableAmount() {
        return curPayableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.cur_payable_amount
     *
     * @param curPayableAmount the value for settle_account.cur_payable_amount
     *
     * @mbggenerated
     */
    public void setCurPayableAmount(Double curPayableAmount) {
        this.curPayableAmount = curPayableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.sum_surplus_amount
     *
     * @return the value of settle_account.sum_surplus_amount
     *
     * @mbggenerated
     */
    public Double getSumSurplusAmount() {
        return sumSurplusAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.sum_surplus_amount
     *
     * @param sumSurplusAmount the value for settle_account.sum_surplus_amount
     *
     * @mbggenerated
     */
    public void setSumSurplusAmount(Double sumSurplusAmount) {
        this.sumSurplusAmount = sumSurplusAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.sum_actual_pay_amount
     *
     * @return the value of settle_account.sum_actual_pay_amount
     *
     * @mbggenerated
     */
    public Double getSumActualPayAmount() {
        return sumActualPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.sum_actual_pay_amount
     *
     * @param sumActualPayAmount the value for settle_account.sum_actual_pay_amount
     *
     * @mbggenerated
     */
    public void setSumActualPayAmount(Double sumActualPayAmount) {
        this.sumActualPayAmount = sumActualPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.sum_payable_amount
     *
     * @return the value of settle_account.sum_payable_amount
     *
     * @mbggenerated
     */
    public Double getSumPayableAmount() {
        return sumPayableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.sum_payable_amount
     *
     * @param sumPayableAmount the value for settle_account.sum_payable_amount
     *
     * @mbggenerated
     */
    public void setSumPayableAmount(Double sumPayableAmount) {
        this.sumPayableAmount = sumPayableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.settle_contract
     *
     * @return the value of settle_account.settle_contract
     *
     * @mbggenerated
     */
    public String getSettleContract() {
        return settleContract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.settle_contract
     *
     * @param settleContract the value for settle_account.settle_contract
     *
     * @mbggenerated
     */
    public void setSettleContract(String settleContract) {
        this.settleContract = settleContract == null ? null : settleContract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_account.settlte_attach
     *
     * @return the value of settle_account.settlte_attach
     *
     * @mbggenerated
     */
    public String getSettleAttach() {
        return settleAttach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_account.settlte_attach
     *
     * @param settleAttach the value for settle_account.settlte_attach
     *
     * @mbggenerated
     */
    public void setSettleAttach(String settleAttach) {
        this.settleAttach = settleAttach == null ? null : settleAttach.trim();
    }
}