package com.banry.pscm.service.workflow;

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

public class ApprovalTrack {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trouble_treat_track.TrackCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private String trackcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trouble_treat_track.TroubleTreatCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private String businesskey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trouble_treat_track.Name
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trouble_treat_track.Claim
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private String claim;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trouble_treat_track.DealTime
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	@JSONField(format="yyyy-MM-dd HH:mm:ss")
	private Date dealtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trouble_treat_track.Dealer
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private String dealer;
	
	private String dealername;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trouble_treat_track.TrackCode
	 * @return  the value of trouble_treat_track.TrackCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public String getTrackcode() {
		return trackcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trouble_treat_track.TrackCode
	 * @param trackcode  the value for trouble_treat_track.TrackCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setTrackcode(String trackcode) {
		this.trackcode = trackcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trouble_treat_track.TroubleTreatCode
	 * @return  the value of trouble_treat_track.TroubleTreatCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public String getBusinesskey() {
		return businesskey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trouble_treat_track.TroubleTreatCode
	 * @param businesskey  the value for trouble_treat_track.TroubleTreatCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setBusinesskey(String businesskey) {
		this.businesskey = businesskey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trouble_treat_track.Name
	 * @return  the value of trouble_treat_track.Name
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trouble_treat_track.Name
	 * @param name  the value for trouble_treat_track.Name
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trouble_treat_track.Claim
	 * @return  the value of trouble_treat_track.Claim
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public String getClaim() {
		return claim;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trouble_treat_track.Claim
	 * @param claim  the value for trouble_treat_track.Claim
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setClaim(String claim) {
		this.claim = claim;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trouble_treat_track.DealTime
	 * @return  the value of trouble_treat_track.DealTime
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public Date getDealtime() {
		return dealtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trouble_treat_track.DealTime
	 * @param dealtime  the value for trouble_treat_track.DealTime
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setDealtime(Date dealtime) {
		this.dealtime = dealtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trouble_treat_track.Dealer
	 * @return  the value of trouble_treat_track.Dealer
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public String getDealer() {
		return dealer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trouble_treat_track.Dealer
	 * @param dealer  the value for trouble_treat_track.Dealer
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setDealer(String dealer) {
		this.dealer = dealer;
	}

	/**
	 * @return the dealername
	 */
	public String getDealername() {
		return dealername;
	}

	/**
	 * @param dealername the dealername to set
	 */
	public void setDealername(String dealername) {
		this.dealername = dealername;
	}
}