package com.banry.pscm.persist.mapper;

import org.apache.ibatis.jdbc.SQL;

import com.banry.pscm.service.util.Constant;

public class ConstantSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constant
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public String insertSelective(Constant record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("constant");
        
        if (record.getConstantName() != null) {
            sql.VALUES("constant_name", "#{constantName,jdbcType=VARCHAR}");
        }
        
        if (record.getConstantValue() != null) {
            sql.VALUES("constant_value", "#{constantValue,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.VALUES("remark", "#{remark,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constant
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public String updateByPrimaryKeySelective(Constant record) {
        SQL sql = new SQL();
        sql.UPDATE("constant");
        
        if (record.getConstantValue() != null) {
            sql.SET("constant_value = #{constantValue,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.SET("remark = #{remark,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("constant_name = #{constantName,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    public String selectAll() {
        SQL sql = new SQL();
        sql.SELECT("*");
        sql.FROM("constant");
        return sql.toString();
    }
}