package com.banry.pscm.persist.mapper;

import com.banry.pscm.service.contract.DownContract;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Iterator;
import java.util.Map;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class DownContractSqlProvider {

    private Logger logger = LoggerFactory.getLogger(DownContractSqlProvider.class);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_contract
     *
     * @mbggenerated
     */
    public String insertSelective(DownContract record) {
        BEGIN();
        INSERT_INTO("down_contract");
        
        if (record.getDownContractCode() != null) {
            VALUES("down_contract_code", "#{downContractCode,jdbcType=VARCHAR}");
        }
        
        if (record.getEngCode() != null) {
            VALUES("eng_code", "#{engCode,jdbcType=VARCHAR}");
        }
        
        if (record.getBizType() != null) {
            VALUES("biz_type", "#{bizType,jdbcType=INTEGER}");
        }
        
        if (record.getContractName() != null) {
            VALUES("contract_name", "#{contractName,jdbcType=VARCHAR}");
        }
        
        if (record.getContractPartFirst() != null) {
            VALUES("contract_part_first", "#{contractPartFirst,jdbcType=VARCHAR}");
        }
        
        if (record.getContractPartSecond() != null) {
            VALUES("contract_part_second", "#{contractPartSecond.supplierCreditCode,jdbcType=VARCHAR}");
        }
        
        if (record.getContractPartThird() != null) {
            VALUES("contract_part_third", "#{contractPartThird,jdbcType=VARCHAR}");
        }
        
        if (record.getContractTargetMatter() != null) {
            VALUES("contract_target_matter", "#{contractTargetMatter,jdbcType=VARCHAR}");
        }
        
        if (record.getContractAmount() != null) {
            VALUES("contract_amount", "#{contractAmount,jdbcType=DOUBLE}");
        }
        
        if (record.getExpectedSignDate() != null) {
            VALUES("expected_sign_date", "#{expectedSignDate,jdbcType=DATE}");
        }
        
        if (record.getActualSignDate() != null) {
            VALUES("actual_sign_date", "#{actualSignDate,jdbcType=DATE}");
        }
        
        if (record.getFulfilSpot() != null) {
            VALUES("fulfil_spot", "#{fulfilSpot,jdbcType=VARCHAR}");
        }
        
        if (record.getFulfilDate() != null) {
            VALUES("fulfil_date", "#{fulfilDate,jdbcType=DATE}");
        }
        
        if (record.getFulfilPeriod() != null) {
            VALUES("fulfil_period", "#{fulfilPeriod,jdbcType=INTEGER}");
        }
        
        if (record.getDepositAmount() != null) {
            VALUES("deposit_amount", "#{depositAmount,jdbcType=DOUBLE}");
        }
        
        if (record.getBreakCost() != null) {
            VALUES("break_cost", "#{breakCost,jdbcType=VARCHAR}");
        }
        
        if (record.getRiskLevel() != null) {
            VALUES("risk_level", "#{riskLevel,jdbcType=VARCHAR}");
        }
        
        if (record.getContractPayment() != null) {
            VALUES("contract_payment", "#{contractPayment,jdbcType=VARCHAR}");
        }
        
        if (record.getContractPayRate() != null) {
            VALUES("contract_pay_rate", "#{contractPayRate,jdbcType=DOUBLE}");
        }
        
        if (record.getCorporateAssets() != null) {
            VALUES("corporate_assets", "#{corporateAssets,jdbcType=VARCHAR}");
        }
        
        if (record.getAlarmDate() != null) {
            VALUES("alarm_date", "#{alarmDate,jdbcType=DATE}");
        }
        
        if (record.getStatus() != null) {
            VALUES("status", "#{status,jdbcType=INTEGER}");
        }
        
        if (record.getComtractTmpl() != null) {
            VALUES("comtract_tmpl", "#{comtractTmpl,jdbcType=VARCHAR}");
        }
        
        if (record.getContractAttach() != null) {
            VALUES("contract_attach", "#{contractAttach,jdbcType=VARCHAR}");
        }
        
        if (record.getScanFilePath() != null) {
            VALUES("scan_file_path", "#{scanFilePath,jdbcType=VARCHAR}");
        }
        
        if (record.getTenderResultCode() != null) {
            VALUES("tender_result_code", "#{tenderResultCode,jdbcType=VARCHAR}");
        }

        if (record.getConstructionTeam() != null) {
            VALUES("construction_team", "#{constructionTeam,jdbcType=VARCHAR}");
        }

        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_contract
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(DownContract record) {
        BEGIN();
        UPDATE("down_contract");
        
        if (record.getEngCode() != null) {
            SET("eng_code = #{engCode,jdbcType=VARCHAR}");
        }
        
        if (record.getBizType() != null) {
            SET("biz_type = #{bizType,jdbcType=INTEGER}");
        }
        
        if (record.getContractName() != null) {
            SET("contract_name = #{contractName,jdbcType=VARCHAR}");
        }
        
        if (record.getContractPartFirst() != null) {
            SET("contract_part_first = #{contractPartFirst,jdbcType=VARCHAR}");
        }
        
        if (record.getContractPartSecond() != null) {
            SET("contract_part_second = #{contractPartSecond.supplierCreditCode,jdbcType=VARCHAR}");
        }
        
        if (record.getContractPartThird() != null) {
            SET("contract_part_third = #{contractPartThird,jdbcType=VARCHAR}");
        }
        
        if (record.getContractTargetMatter() != null) {
            SET("contract_target_matter = #{contractTargetMatter,jdbcType=VARCHAR}");
        }
        
        if (record.getContractAmount() != null) {
            SET("contract_amount = #{contractAmount,jdbcType=DOUBLE}");
        }
        
        if (record.getExpectedSignDate() != null) {
            SET("expected_sign_date = #{expectedSignDate,jdbcType=DATE}");
        }
        
        if (record.getActualSignDate() != null) {
            SET("actual_sign_date = #{actualSignDate,jdbcType=DATE}");
        }
        
        if (record.getFulfilSpot() != null) {
            SET("fulfil_spot = #{fulfilSpot,jdbcType=VARCHAR}");
        }
        
        if (record.getFulfilDate() != null) {
            SET("fulfil_date = #{fulfilDate,jdbcType=DATE}");
        }
        
        if (record.getFulfilPeriod() != null) {
            SET("fulfil_period = #{fulfilPeriod,jdbcType=INTEGER}");
        }
        
        if (record.getDepositAmount() != null) {
            SET("deposit_amount = #{depositAmount,jdbcType=DOUBLE}");
        }
        
        if (record.getBreakCost() != null) {
            SET("break_cost = #{breakCost,jdbcType=VARCHAR}");
        }
        
        if (record.getRiskLevel() != null) {
            SET("risk_level = #{riskLevel,jdbcType=VARCHAR}");
        }
        
        if (record.getContractPayment() != null) {
            SET("contract_payment = #{contractPayment,jdbcType=VARCHAR}");
        }
        
        if (record.getContractPayRate() != null) {
            SET("contract_pay_rate = #{contractPayRate,jdbcType=DOUBLE}");
        }
        
        if (record.getCorporateAssets() != null) {
            SET("corporate_assets = #{corporateAssets,jdbcType=VARCHAR}");
        }
        
        if (record.getAlarmDate() != null) {
            SET("alarm_date = #{alarmDate,jdbcType=DATE}");
        }
        
        if (record.getStatus() != null) {
            SET("status = #{status,jdbcType=INTEGER}");
        }
        
        if (record.getComtractTmpl() != null) {
            SET("comtract_tmpl = #{comtractTmpl,jdbcType=VARCHAR}");
        }
        
        if (record.getContractAttach() != null) {
            SET("contract_attach = #{contractAttach,jdbcType=VARCHAR}");
        }
        
        if (record.getScanFilePath() != null) {
            SET("scan_file_path = #{scanFilePath,jdbcType=VARCHAR}");
        }
        
        if (record.getTenderResultCode() != null) {
            SET("tender_result_code = #{tenderResultCode,jdbcType=VARCHAR}");
        }

        if (record.getConstructionTeam() != null) {
            SET("construction_team = #{constructionTeam,jdbcType=VARCHAR}");
        }

        WHERE("down_contract_code = #{downContractCode,jdbcType=VARCHAR}");
        
        return SQL();
    }

    public String findDownContracts(Map<String, Object> map) {
        BEGIN();
        SELECT("*");
        FROM("down_contract");
        if (map.get("biz_type") != null) {
            WHERE("biz_type = " + map.get("biz_type"));
        }
        if (map.get("status") != null) {
            WHERE("status = " + map.get("status"));
        }
        if (map.get("contract_name") != null && map.get("contract_name") != "") {
            WHERE("contract_name like '%" + map.get("contract_name") + "%'");
        }

        return SQL();
    }

    public String findContractsBySupplier(String supplierCreditCode) {
        BEGIN();
        SELECT("*");
        FROM("down_contract");
        WHERE("contract_part_second=#{supplierCreditCode, jdbcType=VARCHAR}");
        WHERE("status <> '99'");
        return SQL();
    }

    public String selectBySQL(Map<String, Object> map) {
        BEGIN();
        SELECT("*");
        FROM("down_contract");
        Iterator<String> iterator = map.keySet().iterator();
        while (iterator.hasNext()) {
            String key = iterator.next();
            Object value = map.get(key);
            if (!key.startsWith("param") && value != null) {
                WHERE(key + "='" + value+"'");
            }
        }
        return SQL();
    }
}