package com.banry.pscm.persist.mapper;

import com.banry.pscm.service.schedule.EngDivisionPlanLinks;
import org.apache.ibatis.jdbc.SQL;

public class EngDivisionPlanLinksSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table eng_division_plan_links
	 * @mbg.generated  Wed Jul 05 23:49:08 CST 2017
	 */
	public String insertSelective(EngDivisionPlanLinks record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("eng_division_plan_links");
		if (record.getId() != null) {
			sql.VALUES("id", "#{id,jdbcType=DECIMAL}");
		}
		if (record.getSource() != null) {
			sql.VALUES("source", "#{source,jdbcType=VARCHAR}");
		}
		if (record.getTarget() != null) {
			sql.VALUES("target", "#{target,jdbcType=VARCHAR}");
		}
		if (record.getType() != null) {
			sql.VALUES("type", "#{type,jdbcType=VARCHAR}");
		}
		if (record.getVersion() != null) {
			sql.VALUES("version", "#{version,jdbcType=VARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table eng_division_plan_links
	 * @mbg.generated  Wed Jul 05 23:49:08 CST 2017
	 */
	public String updateByPrimaryKeySelective(EngDivisionPlanLinks record) {
		SQL sql = new SQL();
		sql.UPDATE("eng_division_plan_links");
		if (record.getSource() != null) {
			sql.SET("source = #{source,jdbcType=VARCHAR}");
		}
		if (record.getTarget() != null) {
			sql.SET("target = #{target,jdbcType=VARCHAR}");
		}
		if (record.getType() != null) {
			sql.SET("type = #{type,jdbcType=VARCHAR}");
		}
		if (record.getVersion() != null) {
			sql.SET("version = #{version,jdbcType=VARCHAR}");
		}
		sql.WHERE("id = #{id,jdbcType=DECIMAL}");
		return sql.toString();
	}
	
	public String selectBySqlWhere(String sqlWhere) {
		SQL sql = new SQL();
		sql.SELECT("a.*");
		sql.FROM("eng_division_plan_links a");
		sql.WHERE(sqlWhere);
		return sql.toString();
	}
}