package com.banry.pscm.persist.mapper;

import com.banry.pscm.service.labour.LaborWages;
import org.apache.ibatis.jdbc.SQL;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class LaborWagesSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor_wages
     *
     * @mbggenerated
     */
    public String insertSelective(LaborWages record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("labor_wages");
        
        if (record.getWageId() != null) {
            sql.VALUES("wage_id", "#{wageId,jdbcType=VARCHAR}");
        }
        
        if (record.getInId() != null) {
            sql.VALUES("in_id", "#{inId,jdbcType=VARCHAR}");
        }
        
        if (record.getYearMonth() != null) {
            sql.VALUES("`year_month`", "#{yearMonth,jdbcType=DATE}");
        }
        
        if (record.getWorkDays() != null) {
            sql.VALUES("work_days", "#{workDays,jdbcType=INTEGER}");
        }
        
        if (record.getWorkedLoads() != null) {
            sql.VALUES("worked_loads", "#{workedLoads,jdbcType=DOUBLE}");
        }
        
        if (record.getGrossPay() != null) {
            sql.VALUES("gross_pay", "#{grossPay,jdbcType=DOUBLE}");
        }
        
        if (record.getNetPay() != null) {
            sql.VALUES("net_pay", "#{netPay,jdbcType=DOUBLE}");
        }
        
        if (record.getRemark() != null) {
            sql.VALUES("remark", "#{remark,jdbcType=LONGVARCHAR}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor_wages
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(LaborWages record) {
        SQL sql = new SQL();
        sql.UPDATE("labor_wages");
        
        if (record.getInId() != null) {
            sql.SET("in_id = #{inId,jdbcType=VARCHAR}");
        }
        
        if (record.getYearMonth() != null) {
            sql.SET("`year_month` = #{yearMonth,jdbcType=DATE}");
        }
        
        if (record.getWorkDays() != null) {
            sql.SET("work_days = #{workDays,jdbcType=INTEGER}");
        }
        
        if (record.getWorkedLoads() != null) {
            sql.SET("worked_loads = #{workedLoads,jdbcType=DOUBLE}");
        }
        
        if (record.getGrossPay() != null) {
            sql.SET("gross_pay = #{grossPay,jdbcType=DOUBLE}");
        }
        
        if (record.getNetPay() != null) {
            sql.SET("net_pay = #{netPay,jdbcType=DOUBLE}");
        }
        
        if (record.getRemark() != null) {
            sql.SET("remark = #{remark,jdbcType=LONGVARCHAR}");
        }

        sql.WHERE("wage_id = #{wageId,jdbcType=VARCHAR}");

        return sql.toString();
    }
}