package com.banry.pscm.persist.mapper;

import com.banry.pscm.service.schedule.ScheduleLabor;
import org.apache.ibatis.jdbc.SQL;

public class ScheduleLaborSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor
     *
     * @mbg.generated Tue Dec 19 22:18:06 CST 2017
     */
    public String insertSelective(ScheduleLabor record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("labor");
        
        if (record.getIdcard() != null) {
            sql.VALUES("idcard", "#{idcard,jdbcType=VARCHAR}");
        }
        
        if (record.getDivisionsncode() != null) {
            sql.VALUES("DivisionSnCode", "#{divisionsncode,jdbcType=VARCHAR}");
        }
        
        if (record.getLabor() != null) {
            sql.VALUES("labor", "#{labor,jdbcType=VARCHAR}");
        }
        
        if (record.getLaborpost() != null) {
            sql.VALUES("laborPost", "#{laborpost,jdbcType=VARCHAR}");
        }
        
        if (record.getLaborcompany() != null) {
            sql.VALUES("laborCompany", "#{laborcompany,jdbcType=VARCHAR}");
        }
        
        if (record.getAcceptTime() != null) {
            sql.VALUES("acceptTime", "#{acceptTime,jdbcType=DATE}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor
     *
     * @mbg.generated Tue Dec 19 22:18:06 CST 2017
     */
    public String updateByPrimaryKeySelective(ScheduleLabor record) {
        SQL sql = new SQL();
        sql.UPDATE("labor");
        
        if (record.getLabor() != null) {
            sql.SET("labor = #{labor,jdbcType=VARCHAR}");
        }
        
        if (record.getLaborpost() != null) {
            sql.SET("laborPost = #{laborpost,jdbcType=VARCHAR}");
        }
        
        if (record.getLaborcompany() != null) {
            sql.SET("laborCompany = #{laborcompany,jdbcType=VARCHAR}");
        }
        
        if (record.getAcceptTime() != null) {
            sql.SET("acceptTime = #{acceptTime,jdbcType=DATE}");
        }
        
        sql.WHERE("idcard = #{idcard,jdbcType=VARCHAR}");
        sql.WHERE("DivisionSnCode = #{divisionsncode,jdbcType=VARCHAR}");
        
        return sql.toString();
    }
}