package com.banry.pscm.persist.mapper;

import com.banry.pscm.service.account.*;
import org.apache.ibatis.jdbc.SQL;

public class SysDeptsSqlProvider {

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_depts
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    public String insertSelective(SysDepts record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("sys_depts");
        
        if (record.getDeptCode() != null) {
            sql.VALUES("dept_code", "#{deptCode,jdbcType=VARCHAR}");
        }
        
        if (record.getTenantCode() != null) {
            sql.VALUES("tenant_code", "#{tenantCode,jdbcType=VARCHAR}");
        }
        
        if (record.getEnterpriseCode() != null) {
            sql.VALUES("enterprise_code", "#{enterpriseCode,jdbcType=VARCHAR}");
        }
        
        if (record.getDeptName() != null) {
            sql.VALUES("dept_name", "#{deptName,jdbcType=VARCHAR}");
        }
        
        if (record.getDeptAddre() != null) {
            sql.VALUES("dept_addre", "#{deptAddre,jdbcType=VARCHAR}");
        }
        
        if (record.getDeptOrganizeDate() != null) {
            sql.VALUES("dept_organize_date", "#{deptOrganizeDate,jdbcType=DATE}");
        }
        
        if (record.getTelephone() != null) {
            sql.VALUES("telephone", "#{telephone,jdbcType=VARCHAR}");
        }
        
        if (record.getMailAddress() != null) {
            sql.VALUES("mail_address", "#{mailAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getLinkManCode() != null) {
            sql.VALUES("link_man_code", "#{linkManCode,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_depts
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    public String updateByPrimaryKeySelective(SysDepts record) {
        SQL sql = new SQL();
        sql.UPDATE("sys_depts");
        
        if (record.getEnterpriseCode() != null) {
            sql.SET("enterprise_code = #{enterpriseCode,jdbcType=VARCHAR}");
        }
        
        if (record.getDeptName() != null) {
            sql.SET("dept_name = #{deptName,jdbcType=VARCHAR}");
        }
        
        if (record.getDeptAddre() != null) {
            sql.SET("dept_addre = #{deptAddre,jdbcType=VARCHAR}");
        }
        
        if (record.getDeptOrganizeDate() != null) {
            sql.SET("dept_organize_date = #{deptOrganizeDate,jdbcType=DATE}");
        }
        
        if (record.getTelephone() != null) {
            sql.SET("telephone = #{telephone,jdbcType=VARCHAR}");
        }
        
        if (record.getMailAddress() != null) {
            sql.SET("mail_address = #{mailAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getLinkManCode() != null) {
            sql.SET("link_man_code = #{linkManCode,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("dept_code = #{deptCode,jdbcType=VARCHAR}");
        sql.WHERE("tenant_code = #{tenantCode,jdbcType=VARCHAR}");
        
        return sql.toString();
    }
}