package com.banry.pscm.persist.mapper;

import com.banry.pscm.service.labour.WorkAttendance;
import org.apache.ibatis.jdbc.SQL;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class WorkAttendanceSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_attendance
     *
     * @mbggenerated
     */
    public String insertSelective(WorkAttendance record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("work_attendance");
        
        if (record.getAttendanceId() != null) {
            sql.VALUES("attendance_id", "#{attendanceId,jdbcType=INTEGER}");
        }
        
        if (record.getInId() != null) {
            sql.VALUES("in_id", "#{inId,jdbcType=VARCHAR}");
        }
        
        if (record.getDay() != null) {
            sql.VALUES("day", "#{day,jdbcType=DATE}");
        }
        
        if (record.getDayInTime() != null) {
            sql.VALUES("day_in_time", "#{dayInTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDayOutTime() != null) {
            sql.VALUES("day_out_time", "#{dayOutTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getWorkedLoad() != null) {
            sql.VALUES("worked_load", "#{workedLoad,jdbcType=DOUBLE}");
        }
        
        if (record.getWorkedLoadUnit() != null) {
            sql.VALUES("worked_load_unit", "#{workedLoadUnit,jdbcType=VARCHAR}");
        }
        
        if (record.getWorkedSpot() != null) {
            sql.VALUES("worked_spot", "#{workedSpot,jdbcType=VARCHAR}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_attendance
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(WorkAttendance record) {
        SQL sql = new SQL();
        sql.UPDATE("work_attendance");
        
        if (record.getInId() != null) {
           sql.SET("in_id = #{inId,jdbcType=VARCHAR}");
        }
        
        if (record.getDay() != null) {
           sql.SET("day = #{day,jdbcType=DATE}");
        }
        
        if (record.getDayInTime() != null) {
           sql.SET("day_in_time = #{dayInTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDayOutTime() != null) {
           sql.SET("day_out_time = #{dayOutTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getWorkedLoad() != null) {
           sql.SET("worked_load = #{workedLoad,jdbcType=DOUBLE}");
        }
        
        if (record.getWorkedLoadUnit() != null) {
           sql.SET("worked_load_unit = #{workedLoadUnit,jdbcType=VARCHAR}");
        }
        
        if (record.getWorkedSpot() != null) {
           sql.SET("worked_spot = #{workedSpot,jdbcType=VARCHAR}");
        }

        sql.WHERE("attendance_id = #{attendanceId,jdbcType=INTEGER}");

        return sql.toString();
    }
}