package com.banry.pscm.service.schedule;

import java.util.Date;

public class EngDivisionPlan extends EngDivisionPlanKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_division_plan.start_date
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_division_plan.end_date
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_division_plan.pre_jobs
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    private String preJobs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_division_plan.version_date
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    private Date versionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_division_plan.version_man_code
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    private String versionManCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_division_plan.start_date
     *
     * @return the value of eng_division_plan.start_date
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_division_plan.start_date
     *
     * @param startDate the value for eng_division_plan.start_date
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_division_plan.end_date
     *
     * @return the value of eng_division_plan.end_date
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_division_plan.end_date
     *
     * @param endDate the value for eng_division_plan.end_date
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_division_plan.pre_jobs
     *
     * @return the value of eng_division_plan.pre_jobs
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public String getPreJobs() {
        return preJobs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_division_plan.pre_jobs
     *
     * @param preJobs the value for eng_division_plan.pre_jobs
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public void setPreJobs(String preJobs) {
        this.preJobs = preJobs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_division_plan.version_date
     *
     * @return the value of eng_division_plan.version_date
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public Date getVersionDate() {
        return versionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_division_plan.version_date
     *
     * @param versionDate the value for eng_division_plan.version_date
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public void setVersionDate(Date versionDate) {
        this.versionDate = versionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_division_plan.version_man_code
     *
     * @return the value of eng_division_plan.version_man_code
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public String getVersionManCode() {
        return versionManCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_division_plan.version_man_code
     *
     * @param versionManCode the value for eng_division_plan.version_man_code
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public void setVersionManCode(String versionManCode) {
        this.versionManCode = versionManCode;
    }
}