package com.banry.pscm.service.schedule;

public class EngDivisionPlanKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_division_plan.division_sn_code
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    private String divisionSnCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_division_plan.div_version
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    private String divVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_division_plan.division_sn_code
     *
     * @return the value of eng_division_plan.division_sn_code
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public String getDivisionSnCode() {
        return divisionSnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_division_plan.division_sn_code
     *
     * @param divisionSnCode the value for eng_division_plan.division_sn_code
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public void setDivisionSnCode(String divisionSnCode) {
        this.divisionSnCode = divisionSnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_division_plan.div_version
     *
     * @return the value of eng_division_plan.div_version
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public String getDivVersion() {
        return divVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_division_plan.div_version
     *
     * @param divVersion the value for eng_division_plan.div_version
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public void setDivVersion(String divVersion) {
        this.divVersion = divVersion;
    }
}