package com.banry.pscm.service.schedule;

import java.math.BigDecimal;

public class EngDivisionPlanLinks {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eng_division_plan_links.id
	 * @mbg.generated  Wed Jul 05 23:49:08 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eng_division_plan_links.source
	 * @mbg.generated  Wed Jul 05 23:49:08 CST 2017
	 */
	private String source;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eng_division_plan_links.target
	 * @mbg.generated  Wed Jul 05 23:49:08 CST 2017
	 */
	private String target;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eng_division_plan_links.type
	 * @mbg.generated  Wed Jul 05 23:49:08 CST 2017
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eng_division_plan_links.version
	 * @mbg.generated  Wed Jul 05 23:49:08 CST 2017
	 */
	private String version;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eng_division_plan_links.id
	 * @return  the value of eng_division_plan_links.id
	 * @mbg.generated  Wed Jul 05 23:49:08 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eng_division_plan_links.id
	 * @param id  the value for eng_division_plan_links.id
	 * @mbg.generated  Wed Jul 05 23:49:08 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eng_division_plan_links.source
	 * @return  the value of eng_division_plan_links.source
	 * @mbg.generated  Wed Jul 05 23:49:08 CST 2017
	 */
	public String getSource() {
		return source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eng_division_plan_links.source
	 * @param source  the value for eng_division_plan_links.source
	 * @mbg.generated  Wed Jul 05 23:49:08 CST 2017
	 */
	public void setSource(String source) {
		this.source = source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eng_division_plan_links.target
	 * @return  the value of eng_division_plan_links.target
	 * @mbg.generated  Wed Jul 05 23:49:08 CST 2017
	 */
	public String getTarget() {
		return target;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eng_division_plan_links.target
	 * @param target  the value for eng_division_plan_links.target
	 * @mbg.generated  Wed Jul 05 23:49:08 CST 2017
	 */
	public void setTarget(String target) {
		this.target = target;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eng_division_plan_links.type
	 * @return  the value of eng_division_plan_links.type
	 * @mbg.generated  Wed Jul 05 23:49:08 CST 2017
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eng_division_plan_links.type
	 * @param type  the value for eng_division_plan_links.type
	 * @mbg.generated  Wed Jul 05 23:49:08 CST 2017
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eng_division_plan_links.version
	 * @return  the value of eng_division_plan_links.version
	 * @mbg.generated  Wed Jul 05 23:49:08 CST 2017
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eng_division_plan_links.version
	 * @param version  the value for eng_division_plan_links.version
	 * @mbg.generated  Wed Jul 05 23:49:08 CST 2017
	 */
	public void setVersion(String version) {
		this.version = version;
	}
}