package com.banry.pscm.service.schedule;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table engineering
 *
 * @mbg.generated do_not_delete_during_merge Sat Jun 23 07:38:26 CST 2018
 */
public class Engineering {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering.eng_code
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    private String engCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering.tenant_code
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    private String tenantCode;

    /**
     * Database Column Remarks:
     *   ??????????????????????????????????
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering.eng_type
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    private Integer engType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering.eng_name
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    private String engName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering.eng_full_name
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    private String engFullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering.eng_address
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    private String engAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering.contract_price
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    private Double contractPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering.budget
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    private Double budget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering.pay_ration_threshold
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    private Double payRationThreshold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering.status
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering.conf_source
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    private String confSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering.eng_survey
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    private String engSurvey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering.eng_code
     *
     * @return the value of engineering.eng_code
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public String getEngCode() {
        return engCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering.eng_code
     *
     * @param engCode the value for engineering.eng_code
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public void setEngCode(String engCode) {
        this.engCode = engCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering.tenant_code
     *
     * @return the value of engineering.tenant_code
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public String getTenantCode() {
        return tenantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering.tenant_code
     *
     * @param tenantCode the value for engineering.tenant_code
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public void setTenantCode(String tenantCode) {
        this.tenantCode = tenantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering.eng_type
     *
     * @return the value of engineering.eng_type
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public Integer getEngType() {
        return engType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering.eng_type
     *
     * @param engType the value for engineering.eng_type
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public void setEngType(Integer engType) {
        this.engType = engType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering.eng_name
     *
     * @return the value of engineering.eng_name
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public String getEngName() {
        return engName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering.eng_name
     *
     * @param engName the value for engineering.eng_name
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public void setEngName(String engName) {
        this.engName = engName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering.eng_full_name
     *
     * @return the value of engineering.eng_full_name
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public String getEngFullName() {
        return engFullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering.eng_full_name
     *
     * @param engFullName the value for engineering.eng_full_name
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public void setEngFullName(String engFullName) {
        this.engFullName = engFullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering.eng_address
     *
     * @return the value of engineering.eng_address
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public String getEngAddress() {
        return engAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering.eng_address
     *
     * @param engAddress the value for engineering.eng_address
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public void setEngAddress(String engAddress) {
        this.engAddress = engAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering.contract_price
     *
     * @return the value of engineering.contract_price
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public Double getContractPrice() {
        return contractPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering.contract_price
     *
     * @param contractPrice the value for engineering.contract_price
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public void setContractPrice(Double contractPrice) {
        this.contractPrice = contractPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering.budget
     *
     * @return the value of engineering.budget
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public Double getBudget() {
        return budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering.budget
     *
     * @param budget the value for engineering.budget
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public void setBudget(Double budget) {
        this.budget = budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering.pay_ration_threshold
     *
     * @return the value of engineering.pay_ration_threshold
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public Double getPayRationThreshold() {
        return payRationThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering.pay_ration_threshold
     *
     * @param payRationThreshold the value for engineering.pay_ration_threshold
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public void setPayRationThreshold(Double payRationThreshold) {
        this.payRationThreshold = payRationThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering.status
     *
     * @return the value of engineering.status
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering.status
     *
     * @param status the value for engineering.status
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering.conf_source
     *
     * @return the value of engineering.conf_source
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public String getConfSource() {
        return confSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering.conf_source
     *
     * @param confSource the value for engineering.conf_source
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public void setConfSource(String confSource) {
        this.confSource = confSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering.eng_survey
     *
     * @return the value of engineering.eng_survey
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public String getEngSurvey() {
        return engSurvey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering.eng_survey
     *
     * @param engSurvey the value for engineering.eng_survey
     *
     * @mbg.generated Sat Jun 23 07:38:26 CST 2018
     */
    public void setEngSurvey(String engSurvey) {
        this.engSurvey = engSurvey;
    }
    

	@Override
	public String toString() {
		return "Engineering [engCode=" + engCode + ", tenantCode=" + tenantCode + ", engType=" + engType + ", engName="
				+ engName + ", engFullName=" + engFullName + ", engAddress=" + engAddress + ", contractPrice="
				+ contractPrice + ", budget=" + budget + ", payRationThreshold=" + payRationThreshold + ", status="
				+ status + ", confSource=" + confSource + ", engSurvey=" + engSurvey + "]";
	}
    
    
}