package com.banry.pscm.service.schedule;

public class RoleDivision {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_division.role_div_code
     *
     * @mbg.generated Fri Jul 13 09:45:52 CST 2018
     */
    private String roleDivCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_division.role_code
     *
     * @mbg.generated Fri Jul 13 09:45:52 CST 2018
     */
    private String roleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_division.div_code
     *
     * @mbg.generated Fri Jul 13 09:45:52 CST 2018
     */
    private String divCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_division.tenant_code
     *
     * @mbg.generated Fri Jul 13 09:45:52 CST 2018
     */
    private String tenantCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_division.role_div_code
     *
     * @return the value of role_division.role_div_code
     *
     * @mbg.generated Fri Jul 13 09:45:52 CST 2018
     */
    public String getRoleDivCode() {
        return roleDivCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_division.role_div_code
     *
     * @param roleDivCode the value for role_division.role_div_code
     *
     * @mbg.generated Fri Jul 13 09:45:52 CST 2018
     */
    public void setRoleDivCode(String roleDivCode) {
        this.roleDivCode = roleDivCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_division.role_code
     *
     * @return the value of role_division.role_code
     *
     * @mbg.generated Fri Jul 13 09:45:52 CST 2018
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_division.role_code
     *
     * @param roleCode the value for role_division.role_code
     *
     * @mbg.generated Fri Jul 13 09:45:52 CST 2018
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_division.div_code
     *
     * @return the value of role_division.div_code
     *
     * @mbg.generated Fri Jul 13 09:45:52 CST 2018
     */
    public String getDivCode() {
        return divCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_division.div_code
     *
     * @param divCode the value for role_division.div_code
     *
     * @mbg.generated Fri Jul 13 09:45:52 CST 2018
     */
    public void setDivCode(String divCode) {
        this.divCode = divCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_division.tenant_code
     *
     * @return the value of role_division.tenant_code
     *
     * @mbg.generated Fri Jul 13 09:45:52 CST 2018
     */
    public String getTenantCode() {
        return tenantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_division.tenant_code
     *
     * @param tenantCode the value for role_division.tenant_code
     *
     * @mbg.generated Fri Jul 13 09:45:52 CST 2018
     */
    public void setTenantCode(String tenantCode) {
        this.tenantCode = tenantCode;
    }
}