package com.banry.pscm.service.schedule;

public class SubDivWorkChangeBillKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_div_work_change_bill.division_sn_code
     *
     * @mbggenerated
     */
    private String divisionSnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_div_work_change_bill.change_code
     *
     * @mbggenerated
     */
    private String changeCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_div_work_change_bill.division_sn_code
     *
     * @return the value of sub_div_work_change_bill.division_sn_code
     *
     * @mbggenerated
     */
    public String getDivisionSnCode() {
        return divisionSnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_div_work_change_bill.division_sn_code
     *
     * @param divisionSnCode the value for sub_div_work_change_bill.division_sn_code
     *
     * @mbggenerated
     */
    public void setDivisionSnCode(String divisionSnCode) {
        this.divisionSnCode = divisionSnCode == null ? null : divisionSnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_div_work_change_bill.change_code
     *
     * @return the value of sub_div_work_change_bill.change_code
     *
     * @mbggenerated
     */
    public String getChangeCode() {
        return changeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_div_work_change_bill.change_code
     *
     * @param changeCode the value for sub_div_work_change_bill.change_code
     *
     * @mbggenerated
     */
    public void setChangeCode(String changeCode) {
        this.changeCode = changeCode == null ? null : changeCode.trim();
    }
}