package com.banry.pscm.service.schedule;

import com.banry.pscm.service.contract.DownContractChange;
import com.banry.pscm.service.enums.ChangeTypeEnum;

public class SubDivWorkChangeBill extends SubDivWorkChangeBillKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_div_work_change_bill.change_type
     *
     * @mbggenerated
     */
    private ChangeTypeEnum changeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_div_work_change_bill.supplier_credit_code
     *
     * @mbggenerated
     */
    private String supplierCreditCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_div_work_change_bill.eng_num_before
     *
     * @mbggenerated
     */
    private Double engNumBefore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_div_work_change_bill.eng_num_change
     *
     * @mbggenerated
     */
    private Double engNumChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_div_work_change_bill.eng_num_after
     *
     * @mbggenerated
     */
    private Double engNumAfter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_div_work_change_bill.unit_price_before
     *
     * @mbggenerated
     */
    private Double unitPriceBefore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_div_work_change_bill.unit_price_change
     *
     * @mbggenerated
     */
    private Double unitPriceChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_div_work_change_bill.unit_price_after
     *
     * @mbggenerated
     */
    private Double unitPriceAfter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_div_work_change_bill.changed_contract_code
     *
     * @mbggenerated
     */
    private String changedContractCode;

    private DownContractChange contractChange;

    private SubDivWorkBill subDivWorkBill;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_div_work_change_bill.change_type
     *
     * @return the value of sub_div_work_change_bill.change_type
     *
     * @mbggenerated
     */
    public ChangeTypeEnum getChangeType() {
        return changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_div_work_change_bill.change_type
     *
     * @param changeType the value for sub_div_work_change_bill.change_type
     *
     * @mbggenerated
     */
    public void setChangeType(ChangeTypeEnum changeType) {
        this.changeType = changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_div_work_change_bill.supplier_credit_code
     *
     * @return the value of sub_div_work_change_bill.supplier_credit_code
     *
     * @mbggenerated
     */
    public String getSupplierCreditCode() {
        return supplierCreditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_div_work_change_bill.supplier_credit_code
     *
     * @param supplierCreditCode the value for sub_div_work_change_bill.supplier_credit_code
     *
     * @mbggenerated
     */
    public void setSupplierCreditCode(String supplierCreditCode) {
        this.supplierCreditCode = supplierCreditCode == null ? null : supplierCreditCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_div_work_change_bill.eng_num_before
     *
     * @return the value of sub_div_work_change_bill.eng_num_before
     *
     * @mbggenerated
     */
    public Double getEngNumBefore() {
        return engNumBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_div_work_change_bill.eng_num_before
     *
     * @param engNumBefore the value for sub_div_work_change_bill.eng_num_before
     *
     * @mbggenerated
     */
    public void setEngNumBefore(Double engNumBefore) {
        this.engNumBefore = engNumBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_div_work_change_bill.eng_num_change
     *
     * @return the value of sub_div_work_change_bill.eng_num_change
     *
     * @mbggenerated
     */
    public Double getEngNumChange() {
        return engNumChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_div_work_change_bill.eng_num_change
     *
     * @param engNumChange the value for sub_div_work_change_bill.eng_num_change
     *
     * @mbggenerated
     */
    public void setEngNumChange(Double engNumChange) {
        this.engNumChange = engNumChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_div_work_change_bill.eng_num_after
     *
     * @return the value of sub_div_work_change_bill.eng_num_after
     *
     * @mbggenerated
     */
    public Double getEngNumAfter() {
        return engNumAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_div_work_change_bill.eng_num_after
     *
     * @param engNumAfter the value for sub_div_work_change_bill.eng_num_after
     *
     * @mbggenerated
     */
    public void setEngNumAfter(Double engNumAfter) {
        this.engNumAfter = engNumAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_div_work_change_bill.unit_price_before
     *
     * @return the value of sub_div_work_change_bill.unit_price_before
     *
     * @mbggenerated
     */
    public Double getUnitPriceBefore() {
        return unitPriceBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_div_work_change_bill.unit_price_before
     *
     * @param unitPriceBefore the value for sub_div_work_change_bill.unit_price_before
     *
     * @mbggenerated
     */
    public void setUnitPriceBefore(Double unitPriceBefore) {
        this.unitPriceBefore = unitPriceBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_div_work_change_bill.unit_price_change
     *
     * @return the value of sub_div_work_change_bill.unit_price_change
     *
     * @mbggenerated
     */
    public Double getUnitPriceChange() {
        return unitPriceChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_div_work_change_bill.unit_price_change
     *
     * @param unitPriceChange the value for sub_div_work_change_bill.unit_price_change
     *
     * @mbggenerated
     */
    public void setUnitPriceChange(Double unitPriceChange) {
        this.unitPriceChange = unitPriceChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_div_work_change_bill.unit_price_after
     *
     * @return the value of sub_div_work_change_bill.unit_price_after
     *
     * @mbggenerated
     */
    public Double getUnitPriceAfter() {
        return unitPriceAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_div_work_change_bill.unit_price_after
     *
     * @param unitPriceAfter the value for sub_div_work_change_bill.unit_price_after
     *
     * @mbggenerated
     */
    public void setUnitPriceAfter(Double unitPriceAfter) {
        this.unitPriceAfter = unitPriceAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_div_work_change_bill.changed_contract_code
     *
     * @return the value of sub_div_work_change_bill.changed_contract_code
     *
     * @mbggenerated
     */
    public String getChangedContractCode() {
        return changedContractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_div_work_change_bill.changed_contract_code
     *
     * @param changedContractCode the value for sub_div_work_change_bill.changed_contract_code
     *
     * @mbggenerated
     */
    public void setChangedContractCode(String changedContractCode) {
        this.changedContractCode = changedContractCode == null ? null : changedContractCode.trim();
    }

    public DownContractChange getContractChange() {
        return contractChange;
    }

    public void setContractChange(DownContractChange contractChange) {
        this.contractChange = contractChange;
    }

    public SubDivWorkBill getSubDivWorkBill() {
        return subDivWorkBill;
    }

    public void setSubDivWorkBill(SubDivWorkBill subDivWorkBill) {
        this.subDivWorkBill = subDivWorkBill;
    }
}