package com.banry.pscm.service.schedule;

import java.util.Date;

public class TechDisclosure {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_disclosure.disclosure_code
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    private String disclosureCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_disclosure.division_sn_code
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    private EngDivision divisionSnCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_disclosure.disclosurer
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    private String disclosurer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_disclosure.dis_role
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    private String disRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_disclosure.dis_date
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    private Date disDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_disclosure.dis_level
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    private Integer disLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_disclosure.dis_recipient
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    private String disRecipient;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_disclosure.recipient_role
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    private String recipientRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_disclosure.dis_include
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    private String disInclude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tech_disclosure.disclosure_code
     *
     * @return the value of tech_disclosure.disclosure_code
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public String getDisclosureCode() {
        return disclosureCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tech_disclosure.disclosure_code
     *
     * @param disclosureCode the value for tech_disclosure.disclosure_code
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public void setDisclosureCode(String disclosureCode) {
        this.disclosureCode = disclosureCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tech_disclosure.division_sn_code
     *
     * @return the value of tech_disclosure.division_sn_code
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public EngDivision getDivisionSnCode() {
        return divisionSnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tech_disclosure.division_sn_code
     *
     * @param divisionSnCode the value for tech_disclosure.division_sn_code
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public void setDivisionSnCode(EngDivision divisionSnCode) {
        this.divisionSnCode = divisionSnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tech_disclosure.disclosurer
     *
     * @return the value of tech_disclosure.disclosurer
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public String getDisclosurer() {
        return disclosurer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tech_disclosure.disclosurer
     *
     * @param disclosurer the value for tech_disclosure.disclosurer
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public void setDisclosurer(String disclosurer) {
        this.disclosurer = disclosurer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tech_disclosure.dis_role
     *
     * @return the value of tech_disclosure.dis_role
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public String getDisRole() {
        return disRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tech_disclosure.dis_role
     *
     * @param disRole the value for tech_disclosure.dis_role
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public void setDisRole(String disRole) {
        this.disRole = disRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tech_disclosure.dis_date
     *
     * @return the value of tech_disclosure.dis_date
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public Date getDisDate() {
        return disDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tech_disclosure.dis_date
     *
     * @param disDate the value for tech_disclosure.dis_date
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public void setDisDate(Date disDate) {
        this.disDate = disDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tech_disclosure.dis_level
     *
     * @return the value of tech_disclosure.dis_level
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public Integer getDisLevel() {
        return disLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tech_disclosure.dis_level
     *
     * @param disLevel the value for tech_disclosure.dis_level
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public void setDisLevel(Integer disLevel) {
        this.disLevel = disLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tech_disclosure.dis_recipient
     *
     * @return the value of tech_disclosure.dis_recipient
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public String getDisRecipient() {
        return disRecipient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tech_disclosure.dis_recipient
     *
     * @param disRecipient the value for tech_disclosure.dis_recipient
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public void setDisRecipient(String disRecipient) {
        this.disRecipient = disRecipient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tech_disclosure.recipient_role
     *
     * @return the value of tech_disclosure.recipient_role
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public String getRecipientRole() {
        return recipientRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tech_disclosure.recipient_role
     *
     * @param recipientRole the value for tech_disclosure.recipient_role
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public void setRecipientRole(String recipientRole) {
        this.recipientRole = recipientRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tech_disclosure.dis_include
     *
     * @return the value of tech_disclosure.dis_include
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public String getDisInclude() {
        return disInclude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tech_disclosure.dis_include
     *
     * @param disInclude the value for tech_disclosure.dis_include
     *
     * @mbg.generated Tue Jun 12 14:31:02 CST 2018
     */
    public void setDisInclude(String disInclude) {
        this.disInclude = disInclude;
    }
    
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column tech_disclosure.dis_content
    *
    * @mbg.generated Tue Jun 12 14:31:02 CST 2018
    */
   private String disContent;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column tech_disclosure.dis_attach
    *
    * @mbg.generated Tue Jun 12 14:31:02 CST 2018
    */
   private String disAttach;

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column tech_disclosure.dis_content
    *
    * @return the value of tech_disclosure.dis_content
    *
    * @mbg.generated Tue Jun 12 14:31:02 CST 2018
    */
   public String getDisContent() {
       return disContent;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column tech_disclosure.dis_content
    *
    * @param disContent the value for tech_disclosure.dis_content
    *
    * @mbg.generated Tue Jun 12 14:31:02 CST 2018
    */
   public void setDisContent(String disContent) {
       this.disContent = disContent;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column tech_disclosure.dis_attach
    *
    * @return the value of tech_disclosure.dis_attach
    *
    * @mbg.generated Tue Jun 12 14:31:02 CST 2018
    */
   public String getDisAttach() {
       return disAttach;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column tech_disclosure.dis_attach
    *
    * @param disAttach the value for tech_disclosure.dis_attach
    *
    * @mbg.generated Tue Jun 12 14:31:02 CST 2018
    */
   public void setDisAttach(String disAttach) {
       this.disAttach = disAttach;
   }
}