package com.banry.pscm.service.account;

public class RoleKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_code
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    private String roleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.tenant_code
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    private String tenantCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_code
     *
     * @return the value of role.role_code
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_code
     *
     * @param roleCode the value for role.role_code
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.tenant_code
     *
     * @return the value of role.tenant_code
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    public String getTenantCode() {
        return tenantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.tenant_code
     *
     * @param tenantCode the value for role.tenant_code
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    public void setTenantCode(String tenantCode) {
        this.tenantCode = tenantCode;
    }

	public RoleKey(String roleCode, String tenantCode) {
		super();
		this.roleCode = roleCode;
		this.tenantCode = tenantCode;
	}
	public RoleKey() {
		
	}
}