package com.banry.pscm.service.account;

public class SysResource {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.resource_code
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	private String resourceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.parent_resource_code
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	private String parentResourceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.tenant_code
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	private String tenantCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.resource_name
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	private String resourceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.resource_type
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	private String resourceType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.resource_url
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	private String resourceUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.is_memu
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	private Integer isMemu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.is_dir
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	private Integer isDir;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.status
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.resource_code
	 * @return  the value of sys_resource.resource_code
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	public String getResourceCode() {
		return resourceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.resource_code
	 * @param resourceCode  the value for sys_resource.resource_code
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	public void setResourceCode(String resourceCode) {
		this.resourceCode = resourceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.parent_resource_code
	 * @return  the value of sys_resource.parent_resource_code
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	public String getParentResourceCode() {
		return parentResourceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.parent_resource_code
	 * @param parentResourceCode  the value for sys_resource.parent_resource_code
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	public void setParentResourceCode(String parentResourceCode) {
		this.parentResourceCode = parentResourceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.tenant_code
	 * @return  the value of sys_resource.tenant_code
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	public String getTenantCode() {
		return tenantCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.tenant_code
	 * @param tenantCode  the value for sys_resource.tenant_code
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	public void setTenantCode(String tenantCode) {
		this.tenantCode = tenantCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.resource_name
	 * @return  the value of sys_resource.resource_name
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	public String getResourceName() {
		return resourceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.resource_name
	 * @param resourceName  the value for sys_resource.resource_name
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.resource_type
	 * @return  the value of sys_resource.resource_type
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	public String getResourceType() {
		return resourceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.resource_type
	 * @param resourceType  the value for sys_resource.resource_type
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.resource_url
	 * @return  the value of sys_resource.resource_url
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	public String getResourceUrl() {
		return resourceUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.resource_url
	 * @param resourceUrl  the value for sys_resource.resource_url
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	public void setResourceUrl(String resourceUrl) {
		this.resourceUrl = resourceUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.is_memu
	 * @return  the value of sys_resource.is_memu
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	public Integer getIsMemu() {
		return isMemu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.is_memu
	 * @param isMemu  the value for sys_resource.is_memu
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	public void setIsMemu(Integer isMemu) {
		this.isMemu = isMemu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.is_dir
	 * @return  the value of sys_resource.is_dir
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	public Integer getIsDir() {
		return isDir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.is_dir
	 * @param isDir  the value for sys_resource.is_dir
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	public void setIsDir(Integer isDir) {
		this.isDir = isDir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.status
	 * @return  the value of sys_resource.status
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.status
	 * @param status  the value for sys_resource.status
	 * @mbg.generated  Fri Jul 13 22:06:18 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}