package com.banry.pscm.service.account;

public class SysUsersKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.user_code
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.tenant_code
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    private String tenantCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.user_code
     *
     * @return the value of sys_users.user_code
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.user_code
     *
     * @param userCode the value for sys_users.user_code
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.tenant_code
     *
     * @return the value of sys_users.tenant_code
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    public String getTenantCode() {
        return tenantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.tenant_code
     *
     * @param tenantCode the value for sys_users.tenant_code
     *
     * @mbg.generated Fri Jul 13 09:30:09 CST 2018
     */
    public void setTenantCode(String tenantCode) {
        this.tenantCode = tenantCode;
    }

	public SysUsersKey(String userCode, String tenantCode) {
		super();
		this.userCode = userCode;
		this.tenantCode = tenantCode;
	}
	public SysUsersKey() {
		
	}
}