package com.banry.pscm.service.tender;

import java.sql.Date;

import com.banry.pscm.service.util.EnumVar;

public class BidEvaluationReport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_evaluation_report.bid_result_code
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    private String bidResultCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_evaluation_report.tender_plan_code
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    private TenderPlanWithBLOBs tenderPlanCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_evaluation_report.TenderOpenDate
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    private Date tenderOpenDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_evaluation_report.future_price
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    private Double futurePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_evaluation_report.guide_price
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    private Double guidePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_evaluation_report.tender_open_place
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    private String tenderOpenPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_evaluation_report.evaluate_group_comment
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    private String evaluateGroupComment;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column tender_plan.status
    *
    * @mbg.generated Fri May 25 16:21:28 CST 2018
    */
   private EnumVar status;

   /**
    * 任务ID
    */
   private String taskId;

    private TenderPlan tenderPlan;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_evaluation_report.bid_result_code
     *
     * @return the value of bid_evaluation_report.bid_result_code
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public String getBidResultCode() {
        return bidResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_evaluation_report.bid_result_code
     *
     * @param bidResultCode the value for bid_evaluation_report.bid_result_code
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public void setBidResultCode(String bidResultCode) {
        this.bidResultCode = bidResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_evaluation_report.tender_plan_code
     *
     * @return the value of bid_evaluation_report.tender_plan_code
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public TenderPlanWithBLOBs getTenderPlanCode() {
        return tenderPlanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_evaluation_report.tender_plan_code
     *
     * @param tenderPlanCode the value for bid_evaluation_report.tender_plan_code
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public void setTenderPlanCode(TenderPlanWithBLOBs tenderPlanCode) {
        this.tenderPlanCode = tenderPlanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_evaluation_report.TenderOpenDate
     *
     * @return the value of bid_evaluation_report.TenderOpenDate
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public Date getTenderOpenDate() {
        return tenderOpenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_evaluation_report.TenderOpenDate
     *
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public void setTenderOpenDate(Date tenderOpenDate) {
        this.tenderOpenDate = tenderOpenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_evaluation_report.future_price
     *
     * @return the value of bid_evaluation_report.future_price
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public Double getFuturePrice() {
        return futurePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_evaluation_report.future_price
     *
     * @param futurePrice the value for bid_evaluation_report.future_price
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public void setFuturePrice(Double futurePrice) {
        this.futurePrice = futurePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_evaluation_report.guide_price
     *
     * @return the value of bid_evaluation_report.guide_price
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public Double getGuidePrice() {
        return guidePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_evaluation_report.guide_price
     *
     * @param guidePrice the value for bid_evaluation_report.guide_price
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public void setGuidePrice(Double guidePrice) {
        this.guidePrice = guidePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_evaluation_report.tender_open_place
     *
     * @return the value of bid_evaluation_report.tender_open_place
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public String getTenderOpenPlace() {
        return tenderOpenPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_evaluation_report.tender_open_place
     *
     * @param tenderOpenPlace the value for bid_evaluation_report.tender_open_place
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public void setTenderOpenPlace(String tenderOpenPlace) {
        this.tenderOpenPlace = tenderOpenPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_evaluation_report.evaluate_group_comment
     *
     * @return the value of bid_evaluation_report.evaluate_group_comment
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public String getEvaluateGroupComment() {
        return evaluateGroupComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_evaluation_report.evaluate_group_comment
     *
     * @param evaluateGroupComment the value for bid_evaluation_report.evaluate_group_comment
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public void setEvaluateGroupComment(String evaluateGroupComment) {
        this.evaluateGroupComment = evaluateGroupComment;
    }

    public TenderPlan getTenderPlan() {
        return tenderPlan;
    }

    public void setTenderPlan(TenderPlan tenderPlan) {
        this.tenderPlan = tenderPlan;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tender_plan.status
     *
     * @return the value of tender_plan.status
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public EnumVar getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tender_plan.status
     *
     * @param status the value for tender_plan.status
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public void setStatus(EnumVar status) {
        this.status = status;
    }

	public String getTaskId() {
		return taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}
}