package com.banry.pscm.service.tender;

import java.util.Date;

public class ReleaseTarget {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_target.target_code
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    private String targetCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_target.eeng_code
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    private String engCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_target.tender_plan_code
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    private String tenderPlanCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_target.target_name
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    private String targetName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_target.address
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_target.release_date
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    private Date releaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_target.start_date
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_target.end_date
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    private Date endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_target.target_code
     *
     * @return the value of release_target.target_code
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public String getTargetCode() {
        return targetCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_target.target_code
     *
     * @param targetCode the value for release_target.target_code
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public void setTargetCode(String targetCode) {
        this.targetCode = targetCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_target.eeng_code
     *
     * @return the value of release_target.eeng_code
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public String getEngCode() {
        return engCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_target.eeng_code
     *
     * @param eengCode the value for release_target.eeng_code
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public void setEngCode(String engCode) {
        this.engCode = engCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_target.tender_plan_code
     *
     * @return the value of release_target.tender_plan_code
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public String getTenderPlanCode() {
        return tenderPlanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_target.tender_plan_code
     *
     * @param tenderPlanCode the value for release_target.tender_plan_code
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public void setTenderPlanCode(String tenderPlanCode) {
        this.tenderPlanCode = tenderPlanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_target.target_name
     *
     * @return the value of release_target.target_name
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_target.target_name
     *
     * @param targetName the value for release_target.target_name
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public void setTargetName(String targetName) {
        this.targetName = targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_target.address
     *
     * @return the value of release_target.address
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_target.address
     *
     * @param address the value for release_target.address
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_target.start_date
     *
     * @return the value of release_target.start_date
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_target.start_date
     *
     * @param startDate the value for release_target.start_date
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_target.end_date
     *
     * @return the value of release_target.end_date
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_target.end_date
     *
     * @param endDate the value for release_target.end_date
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

	public Date getReleaseDate() {
		return releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}
}