package com.banry.pscm.service.tender;

import com.banry.pscm.service.enums.ChangeTypeEnum;
import com.banry.pscm.service.util.EnumUtil;

public class SubDivWorkTenderResultChangeBill extends SubDivWorkTenderResultChangeBillKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sub_div_work_tender_result_change_bill.bid_result_code
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	private String bidResultCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sub_div_work_tender_result_change_bill.change_type
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	private Integer changeType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sub_div_work_tender_result_change_bill.eng_num_old
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	private Double engNumOld;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sub_div_work_tender_result_change_bill.eng_num_change
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	private Double engNumChange;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sub_div_work_tender_result_change_bill.eng_num_new
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	private Double engNumNew;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sub_div_work_tender_result_change_bill.unit_price_old
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	private Double unitPriceOld;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sub_div_work_tender_result_change_bill.unit_price_change
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	private Double unitPriceChange;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sub_div_work_tender_result_change_bill.unit_price_new
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	private Double unitPriceNew;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sub_div_work_tender_result_change_bill.change_supplier
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	private Supplier changeSupplier;
	
    public ChangeTypeEnum getChangeTypeEnum() {
        return EnumUtil.getByCode(changeType, ChangeTypeEnum.class);
    }

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sub_div_work_tender_result_change_bill.bid_result_code
	 * @return  the value of sub_div_work_tender_result_change_bill.bid_result_code
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	public String getBidResultCode() {
		return bidResultCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sub_div_work_tender_result_change_bill.bid_result_code
	 * @param bidResultCode  the value for sub_div_work_tender_result_change_bill.bid_result_code
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	public void setBidResultCode(String bidResultCode) {
		this.bidResultCode = bidResultCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sub_div_work_tender_result_change_bill.change_type
	 * @return  the value of sub_div_work_tender_result_change_bill.change_type
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	public Integer getChangeType() {
		return changeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sub_div_work_tender_result_change_bill.change_type
	 * @param changeType  the value for sub_div_work_tender_result_change_bill.change_type
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	public void setChangeType(Integer changeType) {
		this.changeType = changeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sub_div_work_tender_result_change_bill.eng_num_old
	 * @return  the value of sub_div_work_tender_result_change_bill.eng_num_old
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	public Double getEngNumOld() {
		return engNumOld;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sub_div_work_tender_result_change_bill.eng_num_old
	 * @param engNumOld  the value for sub_div_work_tender_result_change_bill.eng_num_old
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	public void setEngNumOld(Double engNumOld) {
		this.engNumOld = engNumOld;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sub_div_work_tender_result_change_bill.eng_num_change
	 * @return  the value of sub_div_work_tender_result_change_bill.eng_num_change
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	public Double getEngNumChange() {
		return engNumChange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sub_div_work_tender_result_change_bill.eng_num_change
	 * @param engNumChange  the value for sub_div_work_tender_result_change_bill.eng_num_change
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	public void setEngNumChange(Double engNumChange) {
		this.engNumChange = engNumChange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sub_div_work_tender_result_change_bill.eng_num_new
	 * @return  the value of sub_div_work_tender_result_change_bill.eng_num_new
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	public Double getEngNumNew() {
		return engNumNew;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sub_div_work_tender_result_change_bill.eng_num_new
	 * @param engNumNew  the value for sub_div_work_tender_result_change_bill.eng_num_new
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	public void setEngNumNew(Double engNumNew) {
		this.engNumNew = engNumNew;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sub_div_work_tender_result_change_bill.unit_price_old
	 * @return  the value of sub_div_work_tender_result_change_bill.unit_price_old
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	public Double getUnitPriceOld() {
		return unitPriceOld;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sub_div_work_tender_result_change_bill.unit_price_old
	 * @param unitPriceOld  the value for sub_div_work_tender_result_change_bill.unit_price_old
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	public void setUnitPriceOld(Double unitPriceOld) {
		this.unitPriceOld = unitPriceOld;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sub_div_work_tender_result_change_bill.unit_price_change
	 * @return  the value of sub_div_work_tender_result_change_bill.unit_price_change
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	public Double getUnitPriceChange() {
		return unitPriceChange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sub_div_work_tender_result_change_bill.unit_price_change
	 * @param unitPriceChange  the value for sub_div_work_tender_result_change_bill.unit_price_change
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	public void setUnitPriceChange(Double unitPriceChange) {
		this.unitPriceChange = unitPriceChange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sub_div_work_tender_result_change_bill.unit_price_new
	 * @return  the value of sub_div_work_tender_result_change_bill.unit_price_new
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	public Double getUnitPriceNew() {
		return unitPriceNew;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sub_div_work_tender_result_change_bill.unit_price_new
	 * @param unitPriceNew  the value for sub_div_work_tender_result_change_bill.unit_price_new
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	public void setUnitPriceNew(Double unitPriceNew) {
		this.unitPriceNew = unitPriceNew;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sub_div_work_tender_result_change_bill.change_supplier
	 * @return  the value of sub_div_work_tender_result_change_bill.change_supplier
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	public Supplier getChangeSupplier() {
		return changeSupplier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sub_div_work_tender_result_change_bill.change_supplier
	 * @param changeSupplier  the value for sub_div_work_tender_result_change_bill.change_supplier
	 * @mbg.generated  Wed Oct 24 09:53:27 CST 2018
	 */
	public void setChangeSupplier(Supplier changeSupplier) {
		this.changeSupplier = changeSupplier;
	}
}