package com.banry.pscm.service.tender;

public class SupplierBidRate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_bid_rate.item_bid_code
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    private String itemBidCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_bid_rate.bid_result_code
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    private String bidResultCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_bid_rate.supplier_credit_code
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    private Supplier supplierCreditCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_bid_rate.first_bid_unit_rate
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    private Double firstBidUnitRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_bid_rate.end_bid_unit_rate
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    private Double endBidUnitRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_bid_rate.item_bid_code
     *
     * @return the value of supplier_bid_rate.item_bid_code
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    public String getItemBidCode() {
        return itemBidCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_bid_rate.item_bid_code
     *
     * @param itemBidCode the value for supplier_bid_rate.item_bid_code
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    public void setItemBidCode(String itemBidCode) {
        this.itemBidCode = itemBidCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_bid_rate.bid_result_code
     *
     * @return the value of supplier_bid_rate.bid_result_code
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    public String getBidResultCode() {
        return bidResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_bid_rate.bid_result_code
     *
     * @param bidResultCode the value for supplier_bid_rate.bid_result_code
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    public void setBidResultCode(String bidResultCode) {
        this.bidResultCode = bidResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_bid_rate.supplier_credit_code
     *
     * @return the value of supplier_bid_rate.supplier_credit_code
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    public Supplier getSupplierCreditCode() {
        return supplierCreditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_bid_rate.supplier_credit_code
     *
     * @param supplierCreditCode the value for supplier_bid_rate.supplier_credit_code
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    public void setSupplierCreditCode(Supplier supplierCreditCode) {
        this.supplierCreditCode = supplierCreditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_bid_rate.first_bid_unit_rate
     *
     * @return the value of supplier_bid_rate.first_bid_unit_rate
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    public Double getFirstBidUnitRate() {
        return firstBidUnitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_bid_rate.first_bid_unit_rate
     *
     * @param firstBidUnitRate the value for supplier_bid_rate.first_bid_unit_rate
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    public void setFirstBidUnitRate(Double firstBidUnitRate) {
        this.firstBidUnitRate = firstBidUnitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_bid_rate.end_bid_unit_rate
     *
     * @return the value of supplier_bid_rate.end_bid_unit_rate
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    public Double getEndBidUnitRate() {
        return endBidUnitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_bid_rate.end_bid_unit_rate
     *
     * @param endBidUnitRate the value for supplier_bid_rate.end_bid_unit_rate
     *
     * @mbg.generated Fri Aug 03 16:03:39 CST 2018
     */
    public void setEndBidUnitRate(Double endBidUnitRate) {
        this.endBidUnitRate = endBidUnitRate;
    }
}