package com.banry.pscm.service.tender;

public class TenderResultChangeBill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tender_result_change_bill.division_sn_code
     *
     * @mbg.generated Wed May 30 10:40:14 CST 2018
     */
    private String divisionSnCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tender_result_change_bill.tender_result_id_change_code
     *
     * @mbg.generated Wed May 30 10:40:14 CST 2018
     */
    private String tenderResultIdChangeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tender_result_change_bill.pre_bid_result_code
     *
     * @mbg.generated Wed May 30 10:40:14 CST 2018
     */
    private String preBidResultCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tender_result_change_bill.post_bid_result_code
     *
     * @mbg.generated Wed May 30 10:40:14 CST 2018
     */
    private String postBidResultCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tender_result_change_bill.pre_unit_price
     *
     * @mbg.generated Wed May 30 10:40:14 CST 2018
     */
    private String preUnitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tender_result_change_bill.post_unit_price
     *
     * @mbg.generated Wed May 30 10:40:14 CST 2018
     */
    private String postUnitPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tender_result_change_bill.division_sn_code
     *
     * @return the value of tender_result_change_bill.division_sn_code
     *
     * @mbg.generated Wed May 30 10:40:14 CST 2018
     */
    public String getDivisionSnCode() {
        return divisionSnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tender_result_change_bill.division_sn_code
     *
     * @param divisionSnCode the value for tender_result_change_bill.division_sn_code
     *
     * @mbg.generated Wed May 30 10:40:14 CST 2018
     */
    public void setDivisionSnCode(String divisionSnCode) {
        this.divisionSnCode = divisionSnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tender_result_change_bill.tender_result_id_change_code
     *
     * @return the value of tender_result_change_bill.tender_result_id_change_code
     *
     * @mbg.generated Wed May 30 10:40:14 CST 2018
     */
    public String getTenderResultIdChangeCode() {
        return tenderResultIdChangeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tender_result_change_bill.tender_result_id_change_code
     *
     * @param tenderResultIdChangeCode the value for tender_result_change_bill.tender_result_id_change_code
     *
     * @mbg.generated Wed May 30 10:40:14 CST 2018
     */
    public void setTenderResultIdChangeCode(String tenderResultIdChangeCode) {
        this.tenderResultIdChangeCode = tenderResultIdChangeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tender_result_change_bill.pre_bid_result_code
     *
     * @return the value of tender_result_change_bill.pre_bid_result_code
     *
     * @mbg.generated Wed May 30 10:40:14 CST 2018
     */
    public String getPreBidResultCode() {
        return preBidResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tender_result_change_bill.pre_bid_result_code
     *
     * @param preBidResultCode the value for tender_result_change_bill.pre_bid_result_code
     *
     * @mbg.generated Wed May 30 10:40:14 CST 2018
     */
    public void setPreBidResultCode(String preBidResultCode) {
        this.preBidResultCode = preBidResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tender_result_change_bill.post_bid_result_code
     *
     * @return the value of tender_result_change_bill.post_bid_result_code
     *
     * @mbg.generated Wed May 30 10:40:14 CST 2018
     */
    public String getPostBidResultCode() {
        return postBidResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tender_result_change_bill.post_bid_result_code
     *
     * @param postBidResultCode the value for tender_result_change_bill.post_bid_result_code
     *
     * @mbg.generated Wed May 30 10:40:14 CST 2018
     */
    public void setPostBidResultCode(String postBidResultCode) {
        this.postBidResultCode = postBidResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tender_result_change_bill.pre_unit_price
     *
     * @return the value of tender_result_change_bill.pre_unit_price
     *
     * @mbg.generated Wed May 30 10:40:14 CST 2018
     */
    public String getPreUnitPrice() {
        return preUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tender_result_change_bill.pre_unit_price
     *
     * @param preUnitPrice the value for tender_result_change_bill.pre_unit_price
     *
     * @mbg.generated Wed May 30 10:40:14 CST 2018
     */
    public void setPreUnitPrice(String preUnitPrice) {
        this.preUnitPrice = preUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tender_result_change_bill.post_unit_price
     *
     * @return the value of tender_result_change_bill.post_unit_price
     *
     * @mbg.generated Wed May 30 10:40:14 CST 2018
     */
    public String getPostUnitPrice() {
        return postUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tender_result_change_bill.post_unit_price
     *
     * @param postUnitPrice the value for tender_result_change_bill.post_unit_price
     *
     * @mbg.generated Wed May 30 10:40:14 CST 2018
     */
    public void setPostUnitPrice(String postUnitPrice) {
        this.postUnitPrice = postUnitPrice;
    }
}