package com.banry.pscm.service.tender;

public class TenderPlanWithBLOBs extends TenderPlan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tender_plan.main_contents
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    private String mainContents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tender_plan.scope_workload
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    private String scopeWorkload;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tender_plan.requirements
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    private String requirements;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tender_plan.main_contents
     *
     * @return the value of tender_plan.main_contents
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public String getMainContents() {
        return mainContents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tender_plan.main_contents
     *
     * @param mainContents the value for tender_plan.main_contents
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public void setMainContents(String mainContents) {
        this.mainContents = mainContents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tender_plan.scope_workload
     *
     * @return the value of tender_plan.scope_workload
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public String getScopeWorkload() {
        return scopeWorkload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tender_plan.scope_workload
     *
     * @param scopeWorkload the value for tender_plan.scope_workload
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public void setScopeWorkload(String scopeWorkload) {
        this.scopeWorkload = scopeWorkload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tender_plan.requirements
     *
     * @return the value of tender_plan.requirements
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public String getRequirements() {
        return requirements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tender_plan.requirements
     *
     * @param requirements the value for tender_plan.requirements
     *
     * @mbg.generated Fri May 25 16:21:28 CST 2018
     */
    public void setRequirements(String requirements) {
        this.requirements = requirements;
    }
}