package com.banry.pscm.service.labour;

import java.util.Date;

public class LaborInOut {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_in_out.in_id
     *
     * @mbggenerated
     */
    private String inId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_in_out.id_number
     *
     * @mbggenerated
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_in_out.in_work_type
     *
     * @mbggenerated
     */
    private Integer inWorkType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_in_out.down_contract_code
     *
     * @mbggenerated
     */
    private String downContractCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_in_out.train_code
     *
     * @mbggenerated
     */
    private String trainCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_in_out.exam_score
     *
     * @mbggenerated
     */
    private Double examScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_in_out.in_date
     *
     * @mbggenerated
     */
    private Date inDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_in_out.out_date
     *
     * @mbggenerated
     */
    private Date outDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_in_out.out_why
     *
     * @mbggenerated
     */
    private String outWhy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_in_out.reamrk
     *
     * @mbggenerated
     */
    private String reamrk;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_in_out.in_id
     *
     * @return the value of labor_in_out.in_id
     *
     * @mbggenerated
     */
    public String getInId() {
        return inId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_in_out.in_id
     *
     * @param inId the value for labor_in_out.in_id
     *
     * @mbggenerated
     */
    public void setInId(String inId) {
        this.inId = inId == null ? null : inId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_in_out.id_number
     *
     * @return the value of labor_in_out.id_number
     *
     * @mbggenerated
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_in_out.id_number
     *
     * @param idNumber the value for labor_in_out.id_number
     *
     * @mbggenerated
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_in_out.in_work_type
     *
     * @return the value of labor_in_out.in_work_type
     *
     * @mbggenerated
     */
    public Integer getInWorkType() {
        return inWorkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_in_out.in_work_type
     *
     * @param inWorkType the value for labor_in_out.in_work_type
     *
     * @mbggenerated
     */
    public void setInWorkType(Integer inWorkType) {
        this.inWorkType = inWorkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_in_out.down_contract_code
     *
     * @return the value of labor_in_out.down_contract_code
     *
     * @mbggenerated
     */
    public String getDownContractCode() {
        return downContractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_in_out.down_contract_code
     *
     * @param downContractCode the value for labor_in_out.down_contract_code
     *
     * @mbggenerated
     */
    public void setDownContractCode(String downContractCode) {
        this.downContractCode = downContractCode == null ? null : downContractCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_in_out.train_code
     *
     * @return the value of labor_in_out.train_code
     *
     * @mbggenerated
     */
    public String getTrainCode() {
        return trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_in_out.train_code
     *
     * @param trainCode the value for labor_in_out.train_code
     *
     * @mbggenerated
     */
    public void setTrainCode(String trainCode) {
        this.trainCode = trainCode == null ? null : trainCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_in_out.exam_score
     *
     * @return the value of labor_in_out.exam_score
     *
     * @mbggenerated
     */
    public Double getExamScore() {
        return examScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_in_out.exam_score
     *
     * @param examScore the value for labor_in_out.exam_score
     *
     * @mbggenerated
     */
    public void setExamScore(Double examScore) {
        this.examScore = examScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_in_out.in_date
     *
     * @return the value of labor_in_out.in_date
     *
     * @mbggenerated
     */
    public Date getInDate() {
        return inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_in_out.in_date
     *
     * @param inDate the value for labor_in_out.in_date
     *
     * @mbggenerated
     */
    public void setInDate(Date inDate) {
        this.inDate = inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_in_out.out_date
     *
     * @return the value of labor_in_out.out_date
     *
     * @mbggenerated
     */
    public Date getOutDate() {
        return outDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_in_out.out_date
     *
     * @param outDate the value for labor_in_out.out_date
     *
     * @mbggenerated
     */
    public void setOutDate(Date outDate) {
        this.outDate = outDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_in_out.out_why
     *
     * @return the value of labor_in_out.out_why
     *
     * @mbggenerated
     */
    public String getOutWhy() {
        return outWhy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_in_out.out_why
     *
     * @param outWhy the value for labor_in_out.out_why
     *
     * @mbggenerated
     */
    public void setOutWhy(String outWhy) {
        this.outWhy = outWhy == null ? null : outWhy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_in_out.reamrk
     *
     * @return the value of labor_in_out.reamrk
     *
     * @mbggenerated
     */
    public String getReamrk() {
        return reamrk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_in_out.reamrk
     *
     * @param reamrk the value for labor_in_out.reamrk
     *
     * @mbggenerated
     */
    public void setReamrk(String reamrk) {
        this.reamrk = reamrk == null ? null : reamrk.trim();
    }
}