package com.banry.pscm.service.labour;

import java.util.Date;

public class LaborWageBill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_wage_bill.wage_bill_id
     *
     * @mbggenerated
     */
    private String wageBillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_wage_bill.wage_id
     *
     * @mbggenerated
     */
    private String wageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_wage_bill.year_month
     *
     * @mbggenerated
     */
    private Date yearMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_wage_bill.wage_item
     *
     * @mbggenerated
     */
    private String wageItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_wage_bill.wage_item_plus
     *
     * @mbggenerated
     */
    private Integer wageItemPlus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_wage_bill.wage_bill_id
     *
     * @return the value of labor_wage_bill.wage_bill_id
     *
     * @mbggenerated
     */
    public String getWageBillId() {
        return wageBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_wage_bill.wage_bill_id
     *
     * @param wageBillId the value for labor_wage_bill.wage_bill_id
     *
     * @mbggenerated
     */
    public void setWageBillId(String wageBillId) {
        this.wageBillId = wageBillId == null ? null : wageBillId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_wage_bill.wage_id
     *
     * @return the value of labor_wage_bill.wage_id
     *
     * @mbggenerated
     */
    public String getWageId() {
        return wageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_wage_bill.wage_id
     *
     * @param wageId the value for labor_wage_bill.wage_id
     *
     * @mbggenerated
     */
    public void setWageId(String wageId) {
        this.wageId = wageId == null ? null : wageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_wage_bill.year_month
     *
     * @return the value of labor_wage_bill.year_month
     *
     * @mbggenerated
     */
    public Date getYearMonth() {
        return yearMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_wage_bill.year_month
     *
     * @param yearMonth the value for labor_wage_bill.year_month
     *
     * @mbggenerated
     */
    public void setYearMonth(Date yearMonth) {
        this.yearMonth = yearMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_wage_bill.wage_item
     *
     * @return the value of labor_wage_bill.wage_item
     *
     * @mbggenerated
     */
    public String getWageItem() {
        return wageItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_wage_bill.wage_item
     *
     * @param wageItem the value for labor_wage_bill.wage_item
     *
     * @mbggenerated
     */
    public void setWageItem(String wageItem) {
        this.wageItem = wageItem == null ? null : wageItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_wage_bill.wage_item_plus
     *
     * @return the value of labor_wage_bill.wage_item_plus
     *
     * @mbggenerated
     */
    public Integer getWageItemPlus() {
        return wageItemPlus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_wage_bill.wage_item_plus
     *
     * @param wageItemPlus the value for labor_wage_bill.wage_item_plus
     *
     * @mbggenerated
     */
    public void setWageItemPlus(Integer wageItemPlus) {
        this.wageItemPlus = wageItemPlus;
    }
}