package com.banry.pscm.service.labour;

import java.util.Date;

public class LaborWages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_wages.wage_id
     *
     * @mbggenerated
     */
    private String wageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_wages.in_id
     *
     * @mbggenerated
     */
    private String inId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_wages.year_month
     *
     * @mbggenerated
     */
    private Date yearMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_wages.work_days
     *
     * @mbggenerated
     */
    private Integer workDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_wages.worked_loads
     *
     * @mbggenerated
     */
    private Double workedLoads;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_wages.gross_pay
     *
     * @mbggenerated
     */
    private Double grossPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_wages.net_pay
     *
     * @mbggenerated
     */
    private Double netPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_wages.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_wages.wage_id
     *
     * @return the value of labor_wages.wage_id
     *
     * @mbggenerated
     */
    public String getWageId() {
        return wageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_wages.wage_id
     *
     * @param wageId the value for labor_wages.wage_id
     *
     * @mbggenerated
     */
    public void setWageId(String wageId) {
        this.wageId = wageId == null ? null : wageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_wages.in_id
     *
     * @return the value of labor_wages.in_id
     *
     * @mbggenerated
     */
    public String getInId() {
        return inId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_wages.in_id
     *
     * @param inId the value for labor_wages.in_id
     *
     * @mbggenerated
     */
    public void setInId(String inId) {
        this.inId = inId == null ? null : inId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_wages.year_month
     *
     * @return the value of labor_wages.year_month
     *
     * @mbggenerated
     */
    public Date getYearMonth() {
        return yearMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_wages.year_month
     *
     * @param yearMonth the value for labor_wages.year_month
     *
     * @mbggenerated
     */
    public void setYearMonth(Date yearMonth) {
        this.yearMonth = yearMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_wages.work_days
     *
     * @return the value of labor_wages.work_days
     *
     * @mbggenerated
     */
    public Integer getWorkDays() {
        return workDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_wages.work_days
     *
     * @param workDays the value for labor_wages.work_days
     *
     * @mbggenerated
     */
    public void setWorkDays(Integer workDays) {
        this.workDays = workDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_wages.worked_loads
     *
     * @return the value of labor_wages.worked_loads
     *
     * @mbggenerated
     */
    public Double getWorkedLoads() {
        return workedLoads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_wages.worked_loads
     *
     * @param workedLoads the value for labor_wages.worked_loads
     *
     * @mbggenerated
     */
    public void setWorkedLoads(Double workedLoads) {
        this.workedLoads = workedLoads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_wages.gross_pay
     *
     * @return the value of labor_wages.gross_pay
     *
     * @mbggenerated
     */
    public Double getGrossPay() {
        return grossPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_wages.gross_pay
     *
     * @param grossPay the value for labor_wages.gross_pay
     *
     * @mbggenerated
     */
    public void setGrossPay(Double grossPay) {
        this.grossPay = grossPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_wages.net_pay
     *
     * @return the value of labor_wages.net_pay
     *
     * @mbggenerated
     */
    public Double getNetPay() {
        return netPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_wages.net_pay
     *
     * @param netPay the value for labor_wages.net_pay
     *
     * @mbggenerated
     */
    public void setNetPay(Double netPay) {
        this.netPay = netPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_wages.remark
     *
     * @return the value of labor_wages.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_wages.remark
     *
     * @param remark the value for labor_wages.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    @Override
    public String toString() {
        return "LaborWages{" +
                "wageId='" + wageId + '\'' +
                ", inId='" + inId + '\'' +
                ", yearMonth=" + yearMonth +
                ", workDays=" + workDays +
                ", workedLoads=" + workedLoads +
                ", grossPay=" + grossPay +
                ", netPay=" + netPay +
                ", remark='" + remark + '\'' +
                '}';
    }
}