package com.banry.pscm.service.labour;

public class LaborInOutWithBLOBs extends LaborInOut {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_in_out.out_photo
     *
     * @mbggenerated
     */
    private String outPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labor_in_out.in_id_photo
     *
     * @mbggenerated
     */
    private String inIdPhoto;

    private Integer wageModel;
    private Double wageUnitPrice;
    private String wageUmint;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_in_out.out_photo
     *
     * @return the value of labor_in_out.out_photo
     *
     * @mbggenerated
     */
    public String getOutPhoto() {
        return outPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_in_out.out_photo
     *
     * @param outPhoto the value for labor_in_out.out_photo
     *
     * @mbggenerated
     */
    public void setOutPhoto(String outPhoto) {
        this.outPhoto = outPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labor_in_out.in_id_photo
     *
     * @return the value of labor_in_out.in_id_photo
     *
     * @mbggenerated
     */
    public String getInIdPhoto() {
        return inIdPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labor_in_out.in_id_photo
     *
     * @param inIdPhoto the value for labor_in_out.in_id_photo
     *
     * @mbggenerated
     */
    public void setInIdPhoto(String inIdPhoto) {
        this.inIdPhoto = inIdPhoto;
    }


    public Integer getWageModel() {
        return wageModel;
    }

    public void setWageModel(Integer wageModel) {
        this.wageModel = wageModel;
    }

    public Double getWageUnitPrice() {
        return wageUnitPrice;
    }

    public void setWageUnitPrice(Double wageUnitPrice) {
        this.wageUnitPrice = wageUnitPrice;
    }

    public String getWageUmint() {
        return wageUmint;
    }

    public void setWageUmint(String wageUmint) {
        this.wageUmint = wageUmint;
    }
}