package com.banry.pscm.service.labour;

import java.util.Date;

public class WorkAttendance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_attendance.attendance_id
     *
     * @mbggenerated
     */
    private Integer attendanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_attendance.in_id
     *
     * @mbggenerated
     */
    private String inId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_attendance.day
     *
     * @mbggenerated
     */
    private Date day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_attendance.day_in_time
     *
     * @mbggenerated
     */
    private Date dayInTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_attendance.day_out_time
     *
     * @mbggenerated
     */
    private Date dayOutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_attendance.worked_load
     *
     * @mbggenerated
     */
    private Double workedLoad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_attendance.worked_load_unit
     *
     * @mbggenerated
     */
    private String workedLoadUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_attendance.worked_spot
     *
     * @mbggenerated
     */
    private String workedSpot;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_attendance.attendance_id
     *
     * @return the value of work_attendance.attendance_id
     *
     * @mbggenerated
     */
    public Integer getAttendanceId() {
        return attendanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_attendance.attendance_id
     *
     * @param attendanceId the value for work_attendance.attendance_id
     *
     * @mbggenerated
     */
    public void setAttendanceId(Integer attendanceId) {
        this.attendanceId = attendanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_attendance.in_id
     *
     * @return the value of work_attendance.in_id
     *
     * @mbggenerated
     */
    public String getInId() {
        return inId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_attendance.in_id
     *
     * @param inId the value for work_attendance.in_id
     *
     * @mbggenerated
     */
    public void setInId(String inId) {
        this.inId = inId == null ? null : inId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_attendance.day
     *
     * @return the value of work_attendance.day
     *
     * @mbggenerated
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_attendance.day
     *
     * @param day the value for work_attendance.day
     *
     * @mbggenerated
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_attendance.day_in_time
     *
     * @return the value of work_attendance.day_in_time
     *
     * @mbggenerated
     */
    public Date getDayInTime() {
        return dayInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_attendance.day_in_time
     *
     * @param dayInTime the value for work_attendance.day_in_time
     *
     * @mbggenerated
     */
    public void setDayInTime(Date dayInTime) {
        this.dayInTime = dayInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_attendance.day_out_time
     *
     * @return the value of work_attendance.day_out_time
     *
     * @mbggenerated
     */
    public Date getDayOutTime() {
        return dayOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_attendance.day_out_time
     *
     * @param dayOutTime the value for work_attendance.day_out_time
     *
     * @mbggenerated
     */
    public void setDayOutTime(Date dayOutTime) {
        this.dayOutTime = dayOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_attendance.worked_load
     *
     * @return the value of work_attendance.worked_load
     *
     * @mbggenerated
     */
    public Double getWorkedLoad() {
        return workedLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_attendance.worked_load
     *
     * @param workedLoad the value for work_attendance.worked_load
     *
     * @mbggenerated
     */
    public void setWorkedLoad(Double workedLoad) {
        this.workedLoad = workedLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_attendance.worked_load_unit
     *
     * @return the value of work_attendance.worked_load_unit
     *
     * @mbggenerated
     */
    public String getWorkedLoadUnit() {
        return workedLoadUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_attendance.worked_load_unit
     *
     * @param workedLoadUnit the value for work_attendance.worked_load_unit
     *
     * @mbggenerated
     */
    public void setWorkedLoadUnit(String workedLoadUnit) {
        this.workedLoadUnit = workedLoadUnit == null ? null : workedLoadUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_attendance.worked_spot
     *
     * @return the value of work_attendance.worked_spot
     *
     * @mbggenerated
     */
    public String getWorkedSpot() {
        return workedSpot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_attendance.worked_spot
     *
     * @param workedSpot the value for work_attendance.worked_spot
     *
     * @mbggenerated
     */
    public void setWorkedSpot(String workedSpot) {
        this.workedSpot = workedSpot == null ? null : workedSpot.trim();
    }
}